### ISSUE TITLE
tuic-client can NOT load the certificate correctly on MacOS

### ISSUE THREAD

**Issue by ZhiweiYAN** [EAimTY/tuic#102]
Hello, 

- I downloaded the source code of tuic-client and compiled its binary successfully. 
- I use the rcgen to generate certificate files, include cert.pem cert.der, key.pem key.der. 
- But errors happen when the following command:
> `target/debug/tuic-client --server localhost --server-port 5000 --server-ip 127.0.0.1 --token TKN --certificate ../rcgen/certs/cert.pem  --log-level debug --local-port 2088`

Error Messages: 
> Failed to load the certificate: BadDer

I tried several methods to solve it, including 
- using certificate file with **cert.der**, 
- compiling the old version, 
- downloading precompiled x86 versions for mac.

However, the same errors happened. 

I also tried the quinn example in the readme of rcgen github webpage. [link:](https://github.com/est31/rcgen) 
>cargo run
cd ../quinn
cargo run --example server -- --cert ../rcgen/certs/cert.pem --key ../rcgen/certs/key.pem ./
cargo run --example client -- --ca ../rcgen/certs/cert.der https://localhost:4433/README.md

It works.

May I miss something? 

 Thanks.

**Comment by EAimTY** [comment]
I doubt this may be an issue of `rustls` or `webpki`. Some Windows users encountered this too. Did you tried using the same cert file on another platform?

**Comment by ZhiweiYAN** [comment]
I see.  I will be back to post the result after I finish the tries you mentioned.

**Comment by txl263** [comment]
macOS客户端报错
Failed to load the certificate: SignatureAlgorithmMismatch
环境：
OS: macOS 12.6.2 21G320 x86_64

同样一个配置文件（只修改了证书位置）和证书在虚拟机的windows10下运行没有报错

**Comment by EAimTY** [comment]
> Failed to load the certificate: BadDer
> Failed to load the certificate: SignatureAlgorithmMismatch

These errors could be caused by macOS native certificates. The newer version of tuic-client provide an option `disable_native_certs`. This may help to locate the bug
