### ISSUE TITLE
tuic 还是 udp协议，目前依然被qos

### ISSUE THREAD

**Issue by kilvn** [EAimTY/tuic#104]
从hy过来的，难受的是tuic依然使用的是qos协议，试了一下还是被qos了。

浏览网页没问题，外网秒开，但是YouTube跑分只到2000多，tro最高有9w多（但是连接速度慢）。

难受。

**Comment by chika0801** [comment]
建议你换宽带运营商和手机运营商

**Comment by LevineWoo** [comment]
> 从hy过来的，难受的是tuic依然使用的是qos协议，试了一下还是被qos了。
> 
> 浏览网页没问题，外网秒开，但是YouTube跑分只到2000多，tro最高有9w多（但是连接速度慢）。
> 
> 难受。

我本来也是，当时情况是在测试hys和tuic，也有跑speedtest，这样的操作下被qos了，后来等了半个小时左右只用tuic大概持续3个小时，没有被qos，就是正常看视频，这期间youtube一直稳定在10万左右。

**Comment by EAimTY** [comment]
我没有理解你所说的 qos 协议到底是什么，ISP 对 UDP 的 QoS 我也无法替你解决
