### ISSUE TITLE
上游的ring项目已经支持s390x-linux了，能否麻烦发放s390x-linux的运行文件？

### ISSUE THREAD

**Issue by egg1234** [EAimTY/tuic#109]
上游的ring项目已经支持s390x-linux了，基于下面的issues已经completed了

https://github.com/briansmith/ring/issues/1494

能否麻烦发放s390x-linux的运行文件？
谢谢！

**Comment by EAimTY** [comment]
你提到的更改并未进入 ring 的 release，仍需等待上游更新
