### ISSUE TITLE
`[relay] [connection] invalid DNS name: my.server.ip` and what's the recommended way to create cert and private keys?

### ISSUE THREAD

**Issue by greatcat19** [EAimTY/tuic#11]
### Command to start client:

```shell
$ tuic-client -s my.server.ip -p 10081 -t [token] --local-port 10081 --cert ./keys/cert.crt
```

### Server

```shell
./tuic-server -p 10081 -t [token] -c ./keys/cert.crt -k ./keys/pri.key

# how the cert and key were generated:
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout pri.key -out cert.crt
```

I'm not sure whether this is right?

**Comment by EAimTY** [comment]
You should use an end-entity certificate instead of a root certificate on server.

The DNS error is not relevant to cert. Please double check your domain's DNS settings, or use `--server-ip` on client to overwrite the DNS resolve.

**Comment by greatcat19** [comment]
Thanks!

Regarding "an end-entity certificate", do you have a reference?

I found this one: https://gist.github.com/corford/9a206664bb8278c8243821d236665d94#file-gistfile1-txt-L77

**Comment by greatcat19** [comment]
```shell
$ tuic-client --server-ip my.ip.address -p 10081 -t [token] --local-port 10081 --cert ./keys/cert.crt
Required option '--server' missing
```

Does this mean that I must set up a domain for `tuic-server`?
