### ISSUE TITLE
服务端能不能指定DNS出口，以避免DNS泄露？

### ISSUE THREAD

**Issue by maskedeken** [EAimTY/tuic#112]
服务端能不能指定DNS出口，以避免DNS泄露？

**Comment by Coriolauus** [comment]
这个问题也是我很重视的，不仅仅对TUIC来说。
我干脆在服务端部署AdGuard Home，再自己手动修改服务端resolv.conf，将DNS解析指向127.0.0.1:53，也即AdGuard Home监听的地址和端口。

**Comment by gkeyes** [comment]
我也是部署了AdGuard home

**Comment by maskedeken** [comment]
> 我也是部署了AdGuard home

AdGuard太臃肿了

**Comment by Alicazs** [comment]
> 这个问题也是我很重视的，不仅仅对TUIC来说。 我干脆在服务端部署AdGuard Home，再自己手动修改服务端resolv.conf，将DNS解析指向127.0.0.1:53，也即AdGuard Home监听的地址和端口。

那个adguard的dnsproxy可以满足，支持doh dot等，只是没有过滤器

**Comment by Coriolauus** [comment]
> 

DNS Proxy当然也很好，看个人管理需要。
如果说我手上的服务器，不仅每个都部署AdGuard Home，还套娃了mosdns（https://github.com/IrineSistiana/mosdns），那么连AdGuard Home都嫌臃肿的楼主知道后，不是得瞠目结舌？
但是，对DNS有洁癖且管理很严格而精细的我来说，这两个结合才足够满足我的管理要求。

**Comment by Fhokud** [comment]
正确调用socks5 server 可以选择启用代理dns查询（socks5点功能，一般是启用的，取决于socks5客户端行为），实际效果会使用远端服务器设置的DNS。

添加此功能会是软件变得臃肿且不易维护，不建议添加

**Comment by maskedeken** [comment]
> 正确调用socks5 server 可以选择启用代理dns查询（socks5点功能，一般是启用的，取决于socks5客户端行为），实际效果会使用远端服务器设置的DNS。
> 
> 添加此功能会是软件变得臃肿且不易维护，不建议添加

这里说的是服务端，不是客户端

**Comment by Coriolauus** [comment]
Hysteria服务端倒是可以自己指定DNS，且支持的协议相当丰富：UDP/TCP，DoH，DoT，DoQ。
即便如此我也还是将Hysteria的DNS指定到服务端AdGuard Home监听的地址和端口，这么折腾就是为了给我一个完善的DNS管理。
而对NaiveProxy，我就束手无策了，只能在客户端设定好远程DNS，还不能像xray/v2ray那样，服务端开放内网访问后，再指定给本地DNS代理。

**Comment by maskedeken** [comment]
> > 
> 
> DNS Proxy当然也很好，看个人管理需要。 如果说我手上的服务器，不仅每个都部署AdGuard Home，还套娃了mosdns （[https://github.com/IrineSistiana/mosdns）](https://github.com/IrineSistiana/mosdns%EF%BC%89) 那么连AdGuard Home都嫌臃肿的楼主知道后，不是得瞠目结舌？ 但是，对DNS有洁癖且管理很严格而精细的我来说，这两个结合才足够满足我的管理要求。

我现在用unbound，再配合[https://github.com/StevenBlack/hosts](https://github.com/StevenBlack/hosts)做黑名单使用

**Comment by EAimTY** [comment]
See <https://github.com/EAimTY/tuic/tree/dev/tuic-client#opinions-on-advanced-features>
