### ISSUE TITLE
客户端的断线重连

### ISSUE THREAD

**Issue by zzzerow** [EAimTY/tuic#115]
服务端重启，或者断网重连之后tuic客户端无法正常重连

**Comment by hedsbj** [comment]
我也发现，服务端 重启，客户端 也必须 重启才能用

**Comment by First-Dream** [comment]
客户端是不是开启了 `reduce_rtt` ？我测试发现启用 `reduce_rtt` ，重启服务端后只有以下日志
> [2022-12-05T19:43:29Z TRACE] registering event source with poller: token=Token(0), interests=READABLE | WRITABLE
[2022-12-05T19:43:29Z INFO ] Server started. Listening: 0.0.0.0:443
[2022-12-05T19:43:42Z DEBUG] [223.73.45.2:4066] [establish]

需要等待几分钟才能重新连接，禁用 `reduce_rtt` 则重启服务端后客户端几秒内就能重新连接。这两个延迟时间都与客户端 `heartbeat_interval` 有关，但即使 `heartbeat_interval` 设置一个很小的值（如100），启用 `reduce_rtt` 后重新连接的延迟也会比较影响使用体验。比较玄学的是有时会出现已建立的连接正常，而无法建立新连接的问题（如Telegram是长连接所以能正常收发消息，而网页打不开）。

**Comment by chika0801** [comment]
> 服务端重启，或者断网重连之后tuic客户端无法正常重连

此时客户端手动重新加载后，马上就连通了。

> 需要等待几分钟才能重新连接，禁用 reduce_rtt 则重启服务端后客户端几秒内就能重新连接。

无论客户端 关和开 reduce_rtt，服务器重启tuic后，客户端都连不通。手动重启客户端马上通

**Comment by EAimTY** [comment]
新版本更新了心跳机制与 client 的重连机制，理论上解决了这个问题
