### ISSUE TITLE
服务已启动，但端口不通

### ISSUE THREAD

**Issue by BIN-YEE** [EAimTY/tuic#116]
admin@hhhhhh:~$ systemctl status tuic
● tuic.service - TUIC, TUIC's goal is to minimize the handshake latency as much as possible.
     Loaded: loaded (/etc/systemd/system/tuic.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2022-11-18 03:16:20 UTC; 9min ago
       Docs: https://github.com/EAimTY/tuic
   Main PID: 4124 (tuic)
      Tasks: 2 (limit: 1149)
     Memory: 256.0K
        CPU: 1ms
     CGroup: /system.slice/tuic.service
             └─4124 /root/tuic -c /root/tuic_config.json

Nov 18 03:16:20 hhhhhh systemd[1]: Started TUIC, TUIC's goal is to minimize the handshake latency as much as possible..
Nov 18 03:16:20 hhhhhh tuic[4124]: [2022-11-18T03:16:20Z INFO ] Server started. Listening: 0.0.0.0:27496
admin@hhhhhh~$ telnet 0.0.0.0 27496
Trying 0.0.0.0...
telnet: Unable to connect to remote host: Connection refused

**Comment by rampageX** [comment]
telnet 测 UDP 端口？

**Comment by BIN-YEE** [comment]
> telnet 测 UDP 端口？

sorry，我的锅
