### ISSUE TITLE
I hope it can support socks5 out bound

### ISSUE THREAD

**Issue by jantacy** [EAimTY/tuic#120]
https://github.com/XTLS/Xray-core/discussions/593

https://xtls.github.io/document/level-2/warp.html#%E7%94%B3%E8%AF%B7-wrap-%E8%B4%A6%E6%88%B7

and hysteria as another quic proxy software also suppurt it too，https://hysteria.network/docs/advanced-usage/ 

it may be of some help

**Comment by Fhokud** [comment]
#68

**Comment by ggggle** [comment]
> #68

cgroups会把server发给client的流量也重定向，并不可行。除非tuic支持数据包mark标记

**Comment by ggggle** [comment]
作为一个代理服务，它发出的流量可以分为两类：a代理流量；b给客户端的应答流量
我们需要的是将a再经过一层代理，b直接发出去，但是tuic使用cgroups的话无法区分这两种流量，都会经过代理

**Comment by lucifer9** [comment]
有个变通的办法，参考Xray透明代理的配置方式
服务器上用这种办法把所有流量都交给Xray，自然就可以配置分流啥的了
需要注意的一点就是记得iptables里面，对所有客户端的IP直接return
要是客户端没有固定IP地址，就用ipset规则指定对所有国内IP直接return也行

**Comment by zephyrchien** [comment]
真的有这个需求的话还是建议自行fork修改吧， 出站之前多握个手就行。其他方式太折腾了.. 我之前为了方便套warp, 简单粗暴地实现了一下socks5出口 b3f2e26
