### ISSUE TITLE
cloudflare公开了它们rust版本的quic/http3开源实现quiche，与quinn相比，是否有性能提升？

### ISSUE THREAD

**Issue by aa51513** [EAimTY/tuic#123]
是否会考虑将quinn替换成[quiche](https://github.com/cloudflare/quiche)

**Comment by zephyrchien** [comment]
首先需要有人把quiche封装成支持异步调用的形式， 其次需要优化udp收发。这些工作跟quinn和quinn-udp所做的无异， 我认为没有必要重复劳动。

**Comment by zephyrchien** [comment]
> 

回落机制并不需要tuic本体搭载h3的功能，一切都还是在quic的层面上进行的。 服务端只需检查连接建立后收到的第一个`uni stream` 就行了。 (tuic客户端需要先通过`uni stream`发送认证信息; h3客户端需要先通过`uni stream`发起h3层面的`control stream`, 在里面发送`SETTINGS`帧).

**Comment by EAimTY** [comment]
quinn 在设计上更加友好易用，且提供 async API。尽管 quiche 的性能可能更好，但考虑到可维护性与简单性我认为使用 quinn 更佳。
如果感兴趣，你可以考虑实现一个 tuic-quiche 提供给社区。
