### ISSUE TITLE
功能请求：支持自定义 sni 而不是 server ip

### ISSUE THREAD

**Issue by 1715173329** [EAimTY/tuic#126]
`server-ip` 参数起到了自定义 sni 的作用，但只能设定为 ip，在 vps 是动态 ip 的情况下则比较麻烦，需要每次手动更改 ip。
希望能提供一个自定义 sni 的参数，以便可以通过域名连接到 vps。

**Comment by zephyrchien** [comment]
我认为由 `server` 单独决定连接目标, 由 `sni` 指定握手时发送的SNI, 这样才是符合直觉的。 目前的实现是把`server`同时作为连接目标和SNI的值，再由`server-ip`取代连接目标，比较别扭。

**Comment by 1715173329** [comment]
有朋友在泉州，所以为了绕过 sni 封锁是签的 `su.baidu.com` (

**Comment by AtoiX** [comment]
su.baidu.com支持quic不

**Comment by EAimTY** [comment]
#139
