### ISSUE TITLE
mac os 10.13 

### ISSUE THREAD

**Issue by hello1983** [EAimTY/tuic#13]
[2022-03-24T12:32:31Z ERROR] [relay] [connection] endpoint stopping

一直报错这个 请问是什么原因。谢谢

**Comment by EAimTY** [comment]
信息太少，至少把系统架构、使用的 TUIC 架构和运行的命令发上来

**Comment by hello1983** [comment]
linux  debian  11      ./tuic-server -p 1002 -t 125390 -c my.crt -k my.key --congestion-controller bbr

mac os  10.13.    ./tuic-client -s 0.0.0.0 -p 1002 -t 125390 -l 1003 --udp-mode quic --congestion-controller bbr --reduce-rtt

0.0.0.0 为服务器 Linux Debian IP

**Comment by EAimTY** [comment]
`endpoint stopping` 是 TUIC 的上游库 [quinn](https://github.com/quinn-rs/quinn/) 的报错，与 TUIC 本身的实现无关。
Apple 早已停止了 mac os 10.13 的技术支持。为过时的系统提供支持会让开发者工作大量增加，所以这个问题不会被修复。

**Comment by hello1983** [comment]
谢谢 解答。升级是最好的选择。
