### ISSUE TITLE
[功能请求] 多节点轮询/随机负载均衡

### ISSUE THREAD

**Issue by Fhokud** [EAimTY/tuic#130]
便宜小鸡，VLESS_TLS拉到200Mbps满速，CPU75%
TUIC(cubic/BBR)拉到55Mbps左右，CPU100%.......

**Comment by QIN2DIM** [comment]
你什么配置，这都能跑满CPU

**Comment by EAimTY** [comment]
见 <https://github.com/EAimTY/tuic/tree/dev/tuic-server#opinions-on-advanced-features>

**Comment by EAimTY** [comment]
> 如果提交关于高级功能的PR，是否考虑合并？

这里的实现不会增加过多提高复杂度的功能
