### ISSUE TITLE
[功能请求] ①优化流控(更激进地发包) + ②端口跳跃

### ISSUE THREAD

**Issue by aa51513** [EAimTY/tuic#135]
TUIC使用体验整体而言，相当不错
但实际使用过程中，时常会出现断流的问题，这个可能与UDP丢包有关系
是否可以考虑引入类似于Hysteria那样的暴力发包机制，来减缓或者规避此类问题？

除此之外，国内运营商对UDP连接进行QoS，已经是公开的秘密了，同一个端口，达到一定的流量就会被限速
由于QUIC本身对连接的迁移非常友好，也就是说，如果客户端能够主动更换端口，可以很大程度规避此问题

上述两个请求，作者闲暇之余如果看到，还请帮忙评估一下可行性

**Comment by ArcCal** [comment]
qos是个谜

**Comment by aa51513** [comment]
> * 关于问题1，移步 [quinn](https://github.com/quinn-rs/quinn)
>   PS :暴力挤占带宽终将害人害己
> * 关于问题2，TUIC 即将引入http3协议回落以防止主动探测，全新重构的v1.0.0或将在近期发布，此流量行为与Web服务器严重不符
> * 上述功能已被[Hysteria](https://hysteria.network/) 实现

感谢回复

**Comment by ArcCal** [comment]
在我这里，晚上网络拥堵的时候，反倒是tuic速度更快，比常见的走tcp的协议都快
