### ISSUE TITLE
关于tuic断流的问题，我阅读了一下代码，提出一个可优化点

### ISSUE THREAD

**Issue by aa51513** [EAimTY/tuic#137]
目前代码实现逻辑是，连接出现Error的时候，就把连接状态标记为已关闭，然后就啥也不做。

详见代码行
`client/src/relay/incoming.rs:71`

这里的实现逻辑，显然是有可优化空间的
因为一旦连接出错，下一次发起请求，肯定有一个创建连接的过程，在客户端的现象就是断流

一个可以优化的思路是：发现连接出错，客户端就立马自动重连，而不是现在这样等待下次请求发起，再发起重连；
这样可以减缓出现断流问题的可能

**Comment by zephyrchien** [comment]
个人认为cold path没必要大费周折去优化

**Comment by EAimTY** [comment]
> 目前代码实现逻辑是，连接出现Error的时候，就把连接状态标记为已关闭，然后就啥也不做。

断流并非是因此导致的，新的测试版本理论上解决了断流问题。

> 一个可以优化的思路是：发现连接出错，客户端就立马自动重连，而不是现在这样等待下次请求发起，再发起重连；
这样可以减缓出现断流问题的可能

我觉得 server 与 client 之间不应该在连接不活跃时保留连接，由于使用 multiplex，TUIC 建立连接的代价本身较小，所以个人认为惰性地建立连接是更合理的选择。
