### ISSUE TITLE
Support to fill in a domain name in the client's 'IP' field

### ISSUE THREAD

**Issue by yinyue200** [EAimTY/tuic#139]
Currently the contents of the 'server' field appear to be used to validate the certificate, allowing a domain name to be filled in the 'ip' field would allow the server to return a valid certificate for a domain other than its own. This is very useful in case of chained proxies.

**Comment by EAimTY** [comment]
如果需要自定义 SNI，可以在 config field `server` 中使用自定义的 HOST，在 `ip` 中填入真实 IP 地址。注意，所使用的证书的 Common Name 中必须包含自定义的 HOST
