### ISSUE TITLE
[功能请求] tunnel mode 端口转发

### ISSUE THREAD

**Issue by knano** [EAimTY/tuic#144]
可否增加类似 shadowsocks-rust 里的 tunnel 模式用于端口转发。
使用场景类似于 WireGuard over TUIC，如 [Known Limitations](https://www.wireguard.com/known-limitations/) 所说增加 a layer above WireGuard。
目前实现方式可以 tuic 起个 socks 然后再跑个 udp forward over socks 最后跑 wireguard，但感觉性能上有损。

**Comment by virezox** [comment]
有相同需求，想服务器流量直接转发到本机的 socks5 代理端口，类似于 gost 的转发功能。正在看 0.8.5 代码，看看好不好改。

**Comment by EAimTY** [comment]
见 <https://github.com/EAimTY/tuic/tree/dev/tuic-server#opinions-on-advanced-features>
