### ISSUE TITLE
Please add config option and sane default for QUIC's stream receive window

### ISSUE THREAD

**Issue by darhwa** [EAimTY/tuic#149]
The default stream receive window of quinn is only is 1.2MB, which is too conservative. The stream receive window size limits the max bandwidth a stream can reach.

https://github.com/quinn-rs/quinn/blob/37e7b742cbd4cffc2f463358a6cb77149d3b78df/quinn-proto/src/config.rs#L302

For referrence, Google chrome defaults to 6MB, and hysteria uses 15MB.

I suggest setting a bigger default which is enough for most users, as well as adding a config option for power users.

**Comment by mega-optimus** [comment]
Side Note:
In linux we can raise the hard limit by net.core.rmem_max & net.core.wmem_max.
In windows there's no simple equivalence I think, but there are some places for tuning:
https://community.rti.com/static/documentation/perftest/3.0/tuning_os.html
https://docs.nvidia.com/networking/display/winof2v260/Performance+Tuning
https://helpdesk.flexradio.com/hc/en-us/articles/202118518-Optimizing-Ethernet-Adapter-Settings-for-Maximum-Performance

**Comment by EAimTY** [comment]
Configure on `send_window` & `stream_receive_window` is added in cfe9379eb65dc3698d90cdfdbe578fa5ca316523
Now default `stream_receive_window` is 8MiB
