### ISSUE TITLE
“key must be a string ”启动错误1.0

### ISSUE THREAD

**Issue by molezz** [EAimTY/tuic#156]
同样的证书0.8.5使用正常，在1.0版本中用新的json，同样的证书启动提示 “key must be a string ……”

**Comment by EAimTY** [comment]
需要更多细节，你所说的错误是由服务器还是客户端产生？你的配置文件内容？

**Comment by rampageX** [comment]
我估计很大可能是把配的文件的样本`注释`也拷贝进 json 配置文件了。

**Comment by molezz** [comment]
是配置有个注释了， 修订后报 os error 22 了  ， 同样的key  0.85 ok
arm 机器 `./tuic-server-1.0.0-pre-alpha0-aarch64-unknown-linux-musl  -c tuic1.json `

https://github.com/EAimTY/tuic/issues/158
