### ISSUE TITLE
crates.io 安装错误

### ISSUE THREAD

**Issue by Fhokud** [EAimTY/tuic#157]
cargo install tuic-server
# error: could not find `tuic-server` in registry `crates-io` with version `*`

**Comment by molezz** [comment]
我的arm也提示这个 ， 先自己下载release了

**Comment by EAimTY** [comment]
使用 cargo 安装默认会匹配 version `*`，不包含 pre-release version，因此不会匹配到测试版。
可以使用 cargo install 的 `--version` 参数显式定义版本
