### ISSUE TITLE
server启动报错，Invalid argument (os error 22), Protocol not available (os error 92)

### ISSUE THREAD

**Issue by Tsukimeizi** [EAimTY/tuic#158]
版本
./tuic -v
1.0.0-pre-alpha0

配置文件
`{
    "server": "[::]:444",
    "users": {
        "XXXX": "XXXX"
    },
    "certificate": "/etc/fullchain.pem",
    "private_key": "/etc/privkey.pem",
    "congestion_control": "bbr",
    "alpn": ["h3", "spdy/3.1"],
    "udp_relay_ipv6": true,
    "zero_rtt_handshake": false,
    "dual_stack": true,
    "auth_timeout": "5s",
    "max_idle_time": "10s",
    "max_external_packet_size": 1500,
    "gc_interval": "3s",
    "gc_lifetime": "15s",
    "log_level": "info"
}`

$ ./tuic -c ./tuic.json 
Invalid argument (os error 22)

配置文件修改为
`{
    "server": "0.0.0.0:444",
    "users": {
        "XXXX": "XXXX"
    },
    "certificate": "/etc/fullchain.pem",
    "private_key": "/etc/privkey.pem",
    "congestion_control": "bbr",
    "alpn": ["h3", "spdy/3.1"],
    "udp_relay_ipv6": true,
    "zero_rtt_handshake": false,
    "dual_stack": true,
    "auth_timeout": "5s",
    "max_idle_time": "10s",
    "max_external_packet_size": 1500,
    "gc_interval": "3s",
    "gc_lifetime": "15s",
    "log_level": "info"
}`

$ ./tuic -c ./tuic.json 
Protocol not available (os error 92)

**Comment by rampageX** [comment]
这里一样，Oracle 的 aarch64 系统，反正我把一些非必要的删了就可以了，具体那一条懒得试了，下面是能跑起来的配置文件：

```
{
    "server": "[::]:443",
    "users": {
        "00000000-0000-0000-0000-000000000000": "23424234243242"
    },
    "certificate": "/usr/local/nginx/conf/ssl/3344567.xyz.fullchain.cer",
    "private_key": "/usr/local/nginx/conf/ssl/3344567.xyz.key",
    "congestion_control": "bbr",
    "alpn": ["h3", "spdy/3.1"],
    "zero_rtt_handshake": false,
    "log_level": "debug"
}
```

**Comment by pomhg** [comment]
非IPv4/v6双栈vps需要把相关条目删除

**Comment by Tsukimeizi** [comment]
> 非IPv4/v6双栈vps需要把相关条目删除

vps是双栈的

**Comment by pomhg** [comment]
> > 非IPv4/v6双栈vps需要把相关条目删除
> 
> vps是双栈的

我这里即使是双栈的vps启动也会报错，删除dual_stack正常启动，我的server配置文件干脆把udp_relay_ipv6和dual_stack都删掉
#164 大概是这里的问题

**Comment by EAimTY** [comment]
https://github.com/EAimTY/tuic/issues/164#issuecomment-1562930237
