### ISSUE TITLE
Please consider lowering the required version of glibc.

### ISSUE THREAD

**Issue by Blankwonder** [EAimTY/tuic#159]
Currently, version 1.0.0-pre-alpha0-linux-gnu requires glibc version 2.33, which is currently only available in the testing branch of Debian system. Since libc6 is a core dependency, switching only libc6 to the testing channel will cause dependency issues, so the entire system must be upgraded to the testing channel.

If there are no special requirements, please consider lowering the required glibc version.

In addition, the musl version reports an "Protocol not available (os error 92)" error at runtime, and it is uncertain whether it is a configuration issue or a musl version issue.

**Comment by sjmdsky** [comment]
1. [https://github.com/EAimTY/tuic/issues/88#issuecomment-1271131257](url)
2. configuration issue

**Comment by EAimTY** [comment]
glibc version requirement should be lowered to `2.31` in version `1.0.0-pre-alpha1`
