### ISSUE TITLE
speedtest: new tuic vs hysteria

### ISSUE THREAD

**Issue by rampageX** [EAimTY/tuic#161]
先贴结果，同服务器同线路同时间段（Oracle 日本，广州移动千兆光纤，中国时间下午 1 点左右）测 3 次，取最好成绩：

tuic dev:

```
   Speedtest by Ookla

     Server: GSL Networks - Tokyo (id = 50686)
        ISP: Oracle Cloud
    Latency:   113.97 ms   (70.71 ms jitter)
   Download:   525.23 Mbps (data used: 730.6 MB)
     Upload:    40.96 Mbps (data used: 40.6 MB)
Packet Loss:    50.7%
 Result URL: https://www.speedtest.net/result/c/bb59acff-708a-46f1-ba82-18250392a451
```

Hysteria:

```
   Speedtest by Ookla

     Server: i3D.net - Tokyo (id = 21569)
        ISP: Oracle Cloud
    Latency:   117.32 ms   (0.57 ms jitter)
   Download:   237.60 Mbps (data used: 230.3 MB)
     Upload:    32.59 Mbps (data used: 46.6 MB)
Packet Loss:    79.1%
 Result URL: https://www.speedtest.net/result/c/3ba29df7-ab48-4b85-b2c7-a50fcf4c9f42
```

新的 tuic 比 hysteria 要快一倍左右。而且 tuic 下载速度是缓慢上升的，所以推测如果测试数据更大可以跑到更加高的带宽。hysteria 基本在一秒内就能达到峰值带宽，然后稳定在这个峰值。

**Comment by kunger97** [comment]
您这个测度节点都不是一个。能参考吗？

**Comment by rampageX** [comment]
`speedtest -s 28910` 指定节点测速：

tuic：

```
   Speedtest by Ookla

      Server: fdcservers.net - Tokyo (id: 28910)
         ISP: Oracle Cloud
Idle Latency:   112.69 ms   (jitter: 124.32ms, low: 112.63ms, high: 361.23ms)
    Download:   536.29 Mbps (data used: 624.3 MB)
                127.84 ms   (jitter: 32.75ms, low: 112.10ms, high: 342.50ms)
      Upload:    39.54 Mbps (data used: 56.3 MB)
                590.37 ms   (jitter: 90.42ms, low: 111.69ms, high: 1711.01ms)
 Packet Loss: Not available.
  Result URL: https://www.speedtest.net/result/c/e9be5fae-675f-4f2d-b199-8716e864219c
```

hysteria:

```
   Speedtest by Ookla

      Server: fdcservers.net - Tokyo (id: 28910)
         ISP: Oracle Cloud
Idle Latency:   112.69 ms   (jitter: 124.32ms, low: 112.63ms, high: 361.23ms)
    Download:   536.29 Mbps (data used: 624.3 MB)
                127.84 ms   (jitter: 32.75ms, low: 112.10ms, high: 342.50ms)
      Upload:    39.54 Mbps (data used: 56.3 MB)
                590.37 ms   (jitter: 90.42ms, low: 111.69ms, high: 1711.01ms)
 Packet Loss: Not available.
  Result URL: https://www.speedtest.net/result/c/e9be5fae-675f-4f2d-b199-8716e864219c
```

**Comment by kilvn** [comment]
> `speedtest -s 28910` 指定节点测速：
> 
> tuic：
> 
> ```
>    Speedtest by Ookla
> 
>       Server: fdcservers.net - Tokyo (id: 28910)
>          ISP: Oracle Cloud
> Idle Latency:   112.69 ms   (jitter: 124.32ms, low: 112.63ms, high: 361.23ms)
>     Download:   536.29 Mbps (data used: 624.3 MB)
>                 127.84 ms   (jitter: 32.75ms, low: 112.10ms, high: 342.50ms)
>       Upload:    39.54 Mbps (data used: 56.3 MB)
>                 590.37 ms   (jitter: 90.42ms, low: 111.69ms, high: 1711.01ms)
>  Packet Loss: Not available.
>   Result URL: https://www.speedtest.net/result/c/e9be5fae-675f-4f2d-b199-8716e864219c
> ```
> 
> hysteria:
> 
> ```
>    Speedtest by Ookla
> 
>       Server: fdcservers.net - Tokyo (id: 28910)
>          ISP: Oracle Cloud
> Idle Latency:   125.21 ms   (jitter: 0.27ms, low: 125.01ms, high: 125.38ms)
>     Download:   354.15 Mbps (data used: 557.3 MB)
>                 125.68 ms   (jitter: 8.33ms, low: 111.69ms, high: 324.93ms)
>       Upload:    29.98 Mbps (data used: 43.9 MB)
>                 363.04 ms   (jitter: 61.11ms, low: 110.24ms, high: 1646.06ms)
>  Packet Loss: Not available.
>   Result URL: https://www.speedtest.net/result/c/47a6bc27-54af-4242-8bcc-4a720df2bbdd
> ```

hy上下行是多少？在下载带宽高和速度快之间我选择前者。

**Comment by rampageX** [comment]
hysteria 服务端 1000/1000, 客户端 60/1000

**Comment by rampageX** [comment]
中国电信线路：` speedtest -s 28910`

tuic:
```
   Speedtest by Ookla

      Server: fdcservers.net - Tokyo (id: 28910)
         ISP: Oracle Cloud
Idle Latency:   257.76 ms   (jitter: 56.98ms, low: 100.21ms, high: 326.43ms)
    Download:   340.50 Mbps (data used: 492.9 MB)
                159.75 ms   (jitter: 53.09ms, low: 99.18ms, high: 555.95ms)
      Upload:    62.16 Mbps (data used: 96.4 MB)
                244.01 ms   (jitter: 74.53ms, low: 97.92ms, high: 761.36ms)
 Packet Loss: Not available.
  Result URL: https://www.speedtest.net/result/c/d2df83d6-ff73-4117-acb0-9208eb3e1065
```

hysteria:

```
   Speedtest by Ookla

      Server: fdcservers.net - Tokyo (id: 28910)
         ISP: Oracle Cloud
Idle Latency:    99.05 ms   (jitter: 2.45ms, low: 97.70ms, high: 105.72ms)
    Download:   188.42 Mbps (data used: 338.6 MB)
                119.66 ms   (jitter: 32.76ms, low: 98.46ms, high: 325.70ms)
      Upload:    36.45 Mbps (data used: 36.3 MB)
                124.61 ms   (jitter: 41.19ms, low: 96.34ms, high: 475.50ms)
 Packet Loss: Not available.
  Result URL: https://www.speedtest.net/result/c/1af60a80-0f0a-4465-b5f5-746fb98b2605
```

**Comment by wjr050430** [comment]
tuic目前存在一些单线程问题，能否给出单线程结果？

**Comment by rampageX** [comment]
> tuic目前存在一些单线程问题，能否给出单线程结果？

tuic:

```
$ ./speedtest-cli --single --server 28910
Retrieving speedtest.net configuration...
Testing from Oracle Cloud (150.xxx.xxx.xxx)...
Retrieving speedtest.net server list...
Retrieving information for the selected server...
Hosted by fdcservers.net (Tokyo) [42.59 km]: 123.769 ms
Testing download speed................................................................................
Download: 27.89 Mbit/s
Testing upload speed......................................................................................................
Upload: 21.34 Mbit/s
```

hysteria:

```
$ ./speedtest-cli --single --server 28910
Retrieving speedtest.net configuration...
Testing from Oracle Cloud (150.xxx.xxx.xxx)...
Retrieving speedtest.net server list...
Retrieving information for the selected server...
Hosted by fdcservers.net (Tokyo) [42.59 km]: 182.43 ms
Testing download speed................................................................................
Download: 22.92 Mbit/s
Testing upload speed......................................................................................................
Upload: 9.44 Mbit/s
```

**Comment by rampageX** [comment]
延迟特别高的情况下，hysteria 比 tuic 表现要好：(Oracle 荷兰服务器)

tuic: 

```
#speedtest -s 30847

   Speedtest by Ookla

      Server: Claranet Benelux B.V. - Amsterdam (id: 30847)
         ISP: Oracle Cloud
Idle Latency:   554.85 ms   (jitter: 2.45ms, low: 553.25ms, high: 558.64ms)
    Download:    49.00 Mbps (data used: 69.9 MB)
               1163.29 ms   (jitter: 87.48ms, low: 552.00ms, high: 3460.82ms)
      Upload:    49.78 Mbps (data used: 71.1 MB)
               1170.51 ms   (jitter: 83.65ms, low: 545.72ms, high: 2507.37ms)
 Packet Loss:     0.0%
  Result URL: https://www.speedtest.net/result/c/cff00a70-a7f4-4800-a0bd-c5652f9bb21a
```

hysteria:

#speedtest -s 30847

```
   Speedtest by Ookla

      Server: Claranet Benelux B.V. - Amsterdam (id: 30847)
         ISP: Oracle Cloud
Idle Latency:   715.44 ms   (jitter: 585.96ms, low: 524.74ms, high: 1193.85ms)
    Download:   129.46 Mbps (data used: 156.4 MB)
               1416.29 ms   (jitter: 92.37ms, low: 560.22ms, high: 2583.85ms)
      Upload:    10.36 Mbps (data used: 25.5 MB)
               2592.64 ms   (jitter: 94.39ms, low: 568.39ms, high: 5094.87ms)
 Packet Loss:     0.0%
  Result URL: https://www.speedtest.net/result/c/89570c1e-3f64-4ff7-9794-acab09ee47d3
```

**Comment by rampageX** [comment]
Woo, tuic 1.0.0 alpha0:

```
 Speedtest by Ookla

      Server: fdcservers.net - Tokyo (id: 28910)
         ISP: Oracle Cloud
Idle Latency:   522.92 ms   (jitter: 152.96ms, low: 123.73ms, high: 721.41ms)
    Download:   637.50 Mbps (data used: 858.7 MB)
                339.32 ms   (jitter: 70.76ms, low: 125.32ms, high: 1258.58ms)
      Upload:    41.60 Mbps (data used: 73.6 MB)
                614.45 ms   (jitter: 82.31ms, low: 124.14ms, high: 2239.58ms)
 Packet Loss: Not available.
  Result URL: https://www.speedtest.net/result/c/60f01838-166b-4d05-a241-e3f4c27ea58e
```

hysteria:

```
   Speedtest by Ookla

      Server: fdcservers.net - Tokyo (id: 28910)
         ISP: Oracle Cloud
Idle Latency:   116.63 ms   (jitter: 71.66ms, low: 116.33ms, high: 259.48ms)
    Download:   191.92 Mbps (data used: 223.8 MB)
                168.99 ms   (jitter: 47.00ms, low: 107.49ms, high: 543.66ms)
      Upload:    17.33 Mbps (data used: 28.1 MB)
                893.39 ms   (jitter: 87.70ms, low: 111.52ms, high: 3398.06ms)
 Packet Loss: Not available.
  Result URL: https://www.speedtest.net/result/c/73c9b55b-3c4b-4d4e-9a0d-f49b517448d3
```

**Comment by kilvn** [comment]
可以拿 hy v2的测一下

**Comment by rampageX** [comment]
电信 50/500:

hysteria:

```
   Speedtest by Ookla

      Server: fdcservers.net - Tokyo (id: 28910)
         ISP: Oracle Cloud
Idle Latency:    97.21 ms   (jitter: 1.67ms, low: 96.26ms, high: 99.82ms)
    Download:   315.92 Mbps (data used: 427.7 MB)
                139.08 ms   (jitter: 42.53ms, low: 98.61ms, high: 432.78ms)
      Upload:    40.64 Mbps (data used: 44.2 MB)
                125.87 ms   (jitter: 42.73ms, low: 96.39ms, high: 454.33ms)
 Packet Loss: Not available.
  Result URL: https://www.speedtest.net/result/c/4fcb2977-7122-4fde-b153-72d4cf7c2d99
```

[hysteria v2 dev](https://github.com/apernet/hysteria/tree/wip-hy2): (除了必要的端口证书改动，quic 等其它全默认)

```
   Speedtest by Ookla

      Server: fdcservers.net - Tokyo (id: 28910)
         ISP: Oracle Cloud
Idle Latency:   157.38 ms   (jitter: 116.34ms, low: 103.12ms, high: 262.20ms)
    Download:   310.31 Mbps (data used: 317.1 MB)
                238.12 ms   (jitter: 66.65ms, low: 97.37ms, high: 663.24ms)
      Upload:    50.86 Mbps (data used: 80.9 MB)
                385.44 ms   (jitter: 89.28ms, low: 102.04ms, high: 1414.77ms)
 Packet Loss: Not available.
  Result URL: https://www.speedtest.net/result/c/2cfacdc8-e1f7-46b1-8156-e28dca9d130a
```

tuic 1.0.0 alpha0: 

```
   Speedtest by Ookla

      Server: fdcservers.net - Tokyo (id: 28910)
         ISP: Oracle Cloud
Idle Latency:   103.71 ms   (jitter: 354.42ms, low: 101.31ms, high: 810.77ms)
    Download:   422.11 Mbps (data used: 626.5 MB)
                198.44 ms   (jitter: 59.24ms, low: 96.33ms, high: 797.97ms)
      Upload:    64.84 Mbps (data used: 110.1 MB)
                376.36 ms   (jitter: 86.11ms, low: 107.06ms, high: 1131.48ms)
 Packet Loss: Not available.
  Result URL: https://www.speedtest.net/result/c/8dbd6572-67a0-4aa4-a01f-ad466ceb567d
```

**Comment by rampageX** [comment]
移动 50/1000：

 hy:
 	
```
   Speedtest by Ookla

      Server: fdcservers.net - Tokyo (id: 28910)
         ISP: Oracle Cloud
Idle Latency:   115.94 ms   (jitter: 0.36ms, low: 115.57ms, high: 116.28ms)
    Download:   219.40 Mbps (data used: 327.3 MB)
                115.95 ms   (jitter: 20.36ms, low: 112.42ms, high: 336.35ms)
      Upload:    30.53 Mbps (data used: 43.9 MB)
                460.63 ms   (jitter: 73.86ms, low: 111.49ms, high: 2546.01ms)
 Packet Loss: Not available.
  Result URL: https://www.speedtest.net/result/c/307a0b8d-bc7a-4bf0-a8da-19aaf549770d 	
```
 
 
 hy2:
```
   Speedtest by Ookla

      Server: fdcservers.net - Tokyo (id: 28910)
         ISP: Oracle Cloud
Idle Latency:   119.22 ms   (jitter: 0.24ms, low: 118.60ms, high: 119.38ms)
    Download:   261.91 Mbps (data used: 386.8 MB)
                140.71 ms   (jitter: 37.37ms, low: 118.83ms, high: 362.42ms)
      Upload:    38.80 Mbps (data used: 59.1 MB)
                480.36 ms   (jitter: 70.78ms, low: 118.31ms, high: 2124.95ms)
 Packet Loss: Not available.
  Result URL: https://www.speedtest.net/result/c/60562a4d-3782-42b7-9d9c-e32048a8b788
```
  
  tuic:
  	
```
     Speedtest by Ookla

      Server: fdcservers.net - Tokyo (id: 28910)
         ISP: Oracle Cloud
Idle Latency:   124.96 ms   (jitter: 0.25ms, low: 124.61ms, high: 125.23ms)
    Download:   680.62 Mbps (data used: 1.0 GB)
                240.08 ms   (jitter: 59.84ms, low: 124.33ms, high: 665.88ms)
      Upload:    44.55 Mbps (data used: 77.4 MB)
                545.98 ms   (jitter: 85.18ms, low: 129.02ms, high: 1899.30ms)
 Packet Loss: Not available.
  Result URL: https://www.speedtest.net/result/c/8127c8ee-a4c5-462f-b991-c8cb1535873d
```

**Comment by brick2008** [comment]
我也小测了一下，hy 1.3.4 （1078端口）vs tuic1.0.0-beta0  （1080端口）
交替下载ytb视频各3次

tuic主要配置       "password": "xxxxxxx",
        "certificates": ["ca.crt"],
        "udp_relay_mode": "native",
        "congestion_control": "bbr",
        "alpn": ["h3", "spdy/3.1"],
        "zero_rtt_handshake": false,
        "disable_sni": false,

hy主要配置   "obfs": "xxxxxx",
  "server_name": "xxxx.com",
  "ca": "ca.crt",
  "up_mbps": 50,
  "down_mbps": 400,
  "alpn":"h3",
  "fast_open": true,

C:\Users\Administrator>test

C:\Users\Administrator>yt-dlp -6 -f 313 --proxy socks5://127.0.0.1:1078 https://www.youtube.com/watch?v=r5kukRMmZNI -o 1.webm
[youtube] Extracting URL: https://www.youtube.com/watch?v=r5kukRMmZNI
[youtube] r5kukRMmZNI: Downloading webpage
[youtube] r5kukRMmZNI: Downloading android player API JSON
[info] r5kukRMmZNI: Downloading 1 format(s): 313
[dashsegments] Total fragments: 37
[download] Destination: 1.webm
[download] 100% of  366.66MiB in 00:00:29 at 12.63MiB/s

C:\Users\Administrator>timeout 6

等待 0 秒，按一个键继续 ...

C:\Users\Administrator>yt-dlp -6 -f 313 --proxy socks5://127.0.0.1:1080 https://www.youtube.com/watch?v=r5kukRMmZNI -o 2.webm
[youtube] Extracting URL: https://www.youtube.com/watch?v=r5kukRMmZNI
[youtube] r5kukRMmZNI: Downloading webpage
[youtube] r5kukRMmZNI: Downloading android player API JSON
[info] r5kukRMmZNI: Downloading 1 format(s): 313
[dashsegments] Total fragments: 37
[download] Destination: 2.webm
[download] 100% of  366.66MiB in 00:00:24 at 14.73MiB/s

C:\Users\Administrator>timeout 6

等待 0 秒，按一个键继续 ...

C:\Users\Administrator>yt-dlp -6 -f 313 --proxy socks5://127.0.0.1:1078 https://www.youtube.com/watch?v=r5kukRMmZNI -o 3.webm
[youtube] Extracting URL: https://www.youtube.com/watch?v=r5kukRMmZNI
[youtube] r5kukRMmZNI: Downloading webpage
[youtube] r5kukRMmZNI: Downloading android player API JSON
[info] r5kukRMmZNI: Downloading 1 format(s): 313
[dashsegments] Total fragments: 37
[download] Destination: 3.webm
[download] 100% of  366.66MiB in 00:00:28 at 12.75MiB/s

C:\Users\Administrator>timeout 6

等待 0 秒，按一个键继续 ...

C:\Users\Administrator>yt-dlp -6 -f 313 --proxy socks5://127.0.0.1:1080 https://www.youtube.com/watch?v=r5kukRMmZNI -o 4.webm
[youtube] Extracting URL: https://www.youtube.com/watch?v=r5kukRMmZNI
[youtube] r5kukRMmZNI: Downloading webpage
[youtube] r5kukRMmZNI: Downloading android player API JSON
[info] r5kukRMmZNI: Downloading 1 format(s): 313
[dashsegments] Total fragments: 37
[download] Destination: 4.webm
[download] 100% of  366.66MiB in 00:00:26 at 13.58MiB/s

C:\Users\Administrator>timeout 6

等待 0 秒，按一个键继续 ...

C:\Users\Administrator>yt-dlp -6 -f 313 --proxy socks5://127.0.0.1:1078 https://www.youtube.com/watch?v=r5kukRMmZNI -o 5.webm
[youtube] Extracting URL: https://www.youtube.com/watch?v=r5kukRMmZNI
[youtube] r5kukRMmZNI: Downloading webpage
[youtube] r5kukRMmZNI: Downloading android player API JSON
[info] r5kukRMmZNI: Downloading 1 format(s): 313
[dashsegments] Total fragments: 37
[download] Destination: 5.webm
[download] 100% of  366.66MiB in 00:00:30 at 12.17MiB/s

C:\Users\Administrator>timeout 6

等待 0 秒，按一个键继续 ...

C:\Users\Administrator>yt-dlp -6 -f 313 --proxy socks5://127.0.0.1:1080 https://www.youtube.com/watch?v=r5kukRMmZNI -o 6.webm
[youtube] Extracting URL: https://www.youtube.com/watch?v=r5kukRMmZNI
[youtube] r5kukRMmZNI: Downloading webpage
[youtube] r5kukRMmZNI: Downloading android player API JSON
[info] r5kukRMmZNI: Downloading 1 format(s): 313
[dashsegments] Total fragments: 37
[download] Destination: 6.webm
[download] 100% of  366.66MiB in 00:00:27 at 13.54MiB/s

**Comment by CCCAUCHY** [comment]
有没有本地回环测试

**Comment by kilvn** [comment]
> > 我也小测了一下，hy 1.3.4 （1078端口）vs tuic1.0.0-beta0 （1080端口） 交替下载ytb视频各3次
> > tuic主要配置 "password": "xxxxxxx", "certificates": ["ca.crt"], "udp_relay_mode": "native", "congestion_control": "bbr", "alpn": ["h3", "spdy/3.1"], "zero_rtt_handshake": false, "disable_sni": false,
> > hy主要配置 "obfs": "xxxxxx", "server_name": "xxxx.com", "ca": "ca.crt", "up_mbps": 50, "down_mbps": 400, "alpn":"h3", "fast_open": true,
> > C:\Users\Administrator>test
> > C:\Users\Administrator>yt-dlp -6 -f 313 --proxy socks5://127.0.0.1:1078 https://www.youtube.com/watch?v=r5kukRMmZNI -o 1.webm [youtube] Extracting URL: https://www.youtube.com/watch?v=r5kukRMmZNI [youtube] r5kukRMmZNI: Downloading webpage [youtube] r5kukRMmZNI: Downloading android player API JSON [info] r5kukRMmZNI: Downloading 1 format(s): 313 [dashsegments] Total fragments: 37 [download] Destination: 1.webm [download] 100% of 366.66MiB in 00:00:29 at 12.63MiB/s
> > C:\Users\Administrator>timeout 6
> > 等待 0 秒，按一个键继续 ...
> > C:\Users\Administrator>yt-dlp -6 -f 313 --proxy socks5://127.0.0.1:1080 https://www.youtube.com/watch?v=r5kukRMmZNI -o 2.webm [youtube] Extracting URL: https://www.youtube.com/watch?v=r5kukRMmZNI [youtube] r5kukRMmZNI: Downloading webpage [youtube] r5kukRMmZNI: Downloading android player API JSON [info] r5kukRMmZNI: Downloading 1 format(s): 313 [dashsegments] Total fragments: 37 [download] Destination: 2.webm [download] 100% of 366.66MiB in 00:00:24 at 14.73MiB/s
> > C:\Users\Administrator>timeout 6
> > 等待 0 秒，按一个键继续 ...
> > C:\Users\Administrator>yt-dlp -6 -f 313 --proxy socks5://127.0.0.1:1078 https://www.youtube.com/watch?v=r5kukRMmZNI -o 3.webm [youtube] Extracting URL: https://www.youtube.com/watch?v=r5kukRMmZNI [youtube] r5kukRMmZNI: Downloading webpage [youtube] r5kukRMmZNI: Downloading android player API JSON [info] r5kukRMmZNI: Downloading 1 format(s): 313 [dashsegments] Total fragments: 37 [download] Destination: 3.webm [download] 100% of 366.66MiB in 00:00:28 at 12.75MiB/s
> > C:\Users\Administrator>timeout 6
> > 等待 0 秒，按一个键继续 ...
> > C:\Users\Administrator>yt-dlp -6 -f 313 --proxy socks5://127.0.0.1:1080 https://www.youtube.com/watch?v=r5kukRMmZNI -o 4.webm [youtube] Extracting URL: https://www.youtube.com/watch?v=r5kukRMmZNI [youtube] r5kukRMmZNI: Downloading webpage [youtube] r5kukRMmZNI: Downloading android player API JSON [info] r5kukRMmZNI: Downloading 1 format(s): 313 [dashsegments] Total fragments: 37 [download] Destination: 4.webm [download] 100% of 366.66MiB in 00:00:26 at 13.58MiB/s
> > C:\Users\Administrator>timeout 6
> > 等待 0 秒，按一个键继续 ...
> > C:\Users\Administrator>yt-dlp -6 -f 313 --proxy socks5://127.0.0.1:1078 https://www.youtube.com/watch?v=r5kukRMmZNI -o 5.webm [youtube] Extracting URL: https://www.youtube.com/watch?v=r5kukRMmZNI [youtube] r5kukRMmZNI: Downloading webpage [youtube] r5kukRMmZNI: Downloading android player API JSON [info] r5kukRMmZNI: Downloading 1 format(s): 313 [dashsegments] Total fragments: 37 [download] Destination: 5.webm [download] 100% of 366.66MiB in 00:00:30 at 12.17MiB/s
> > C:\Users\Administrator>timeout 6
> > 等待 0 秒，按一个键继续 ...
> > C:\Users\Administrator>yt-dlp -6 -f 313 --proxy socks5://127.0.0.1:1080 https://www.youtube.com/watch?v=r5kukRMmZNI -o 6.webm [youtube] Extracting URL: https://www.youtube.com/watch?v=r5kukRMmZNI [youtube] r5kukRMmZNI: Downloading webpage [youtube] r5kukRMmZNI: Downloading android player API JSON [info] r5kukRMmZNI: Downloading 1 format(s): 313 [dashsegments] Total fragments: 37 [download] Destination: 6.webm [download] 100% of 366.66MiB in 00:00:27 at 13.54MiB/s
> 
> 可以考虑在下面的测试结果里标一下那一部分是tuic，那一部分是hy

没必要吧，人家已经写了 hy 1.3.4 （1078端口）vs tuic1.0.0-beta0 （1080端口）。

**Comment by showgood163** [comment]
> > > 我也小测了一下，hy 1.3.4 （1078端口）vs tuic1.0.0-beta0 （1080端口） 交替下载ytb视频各3次
> > > tuic主要配置 "password": "xxxxxxx", "certificates": ["ca.crt"], "udp_relay_mode": "native", "congestion_control": "bbr", "alpn": ["h3", "spdy/3.1"], "zero_rtt_handshake": false, "disable_sni": false,
> > > hy主要配置 "obfs": "xxxxxx", "server_name": "xxxx.com", "ca": "ca.crt", "up_mbps": 50, "down_mbps": 400, "alpn":"h3", "fast_open": true,
> > > C:\Users\Administrator>test
> > > C:\Users\Administrator>yt-dlp -6 -f 313 --proxy socks5://127.0.0.1:1078 https://www.youtube.com/watch?v=r5kukRMmZNI -o 1.webm [youtube] Extracting URL: https://www.youtube.com/watch?v=r5kukRMmZNI [youtube] r5kukRMmZNI: Downloading webpage [youtube] r5kukRMmZNI: Downloading android player API JSON [info] r5kukRMmZNI: Downloading 1 format(s): 313 [dashsegments] Total fragments: 37 [download] Destination: 1.webm [download] 100% of 366.66MiB in 00:00:29 at 12.63MiB/s
> > > C:\Users\Administrator>timeout 6
> > > 等待 0 秒，按一个键继续 ...
> > > C:\Users\Administrator>yt-dlp -6 -f 313 --proxy socks5://127.0.0.1:1080 https://www.youtube.com/watch?v=r5kukRMmZNI -o 2.webm [youtube] Extracting URL: https://www.youtube.com/watch?v=r5kukRMmZNI [youtube] r5kukRMmZNI: Downloading webpage [youtube] r5kukRMmZNI: Downloading android player API JSON [info] r5kukRMmZNI: Downloading 1 format(s): 313 [dashsegments] Total fragments: 37 [download] Destination: 2.webm [download] 100% of 366.66MiB in 00:00:24 at 14.73MiB/s
> > > C:\Users\Administrator>timeout 6
> > > 等待 0 秒，按一个键继续 ...
> > > C:\Users\Administrator>yt-dlp -6 -f 313 --proxy socks5://127.0.0.1:1078 https://www.youtube.com/watch?v=r5kukRMmZNI -o 3.webm [youtube] Extracting URL: https://www.youtube.com/watch?v=r5kukRMmZNI [youtube] r5kukRMmZNI: Downloading webpage [youtube] r5kukRMmZNI: Downloading android player API JSON [info] r5kukRMmZNI: Downloading 1 format(s): 313 [dashsegments] Total fragments: 37 [download] Destination: 3.webm [download] 100% of 366.66MiB in 00:00:28 at 12.75MiB/s
> > > C:\Users\Administrator>timeout 6
> > > 等待 0 秒，按一个键继续 ...
> > > C:\Users\Administrator>yt-dlp -6 -f 313 --proxy socks5://127.0.0.1:1080 https://www.youtube.com/watch?v=r5kukRMmZNI -o 4.webm [youtube] Extracting URL: https://www.youtube.com/watch?v=r5kukRMmZNI [youtube] r5kukRMmZNI: Downloading webpage [youtube] r5kukRMmZNI: Downloading android player API JSON [info] r5kukRMmZNI: Downloading 1 format(s): 313 [dashsegments] Total fragments: 37 [download] Destination: 4.webm [download] 100% of 366.66MiB in 00:00:26 at 13.58MiB/s
> > > C:\Users\Administrator>timeout 6
> > > 等待 0 秒，按一个键继续 ...
> > > C:\Users\Administrator>yt-dlp -6 -f 313 --proxy socks5://127.0.0.1:1078 https://www.youtube.com/watch?v=r5kukRMmZNI -o 5.webm [youtube] Extracting URL: https://www.youtube.com/watch?v=r5kukRMmZNI [youtube] r5kukRMmZNI: Downloading webpage [youtube] r5kukRMmZNI: Downloading android player API JSON [info] r5kukRMmZNI: Downloading 1 format(s): 313 [dashsegments] Total fragments: 37 [download] Destination: 5.webm [download] 100% of 366.66MiB in 00:00:30 at 12.17MiB/s
> > > C:\Users\Administrator>timeout 6
> > > 等待 0 秒，按一个键继续 ...
> > > C:\Users\Administrator>yt-dlp -6 -f 313 --proxy socks5://127.0.0.1:1080 https://www.youtube.com/watch?v=r5kukRMmZNI -o 6.webm [youtube] Extracting URL: https://www.youtube.com/watch?v=r5kukRMmZNI [youtube] r5kukRMmZNI: Downloading webpage [youtube] r5kukRMmZNI: Downloading android player API JSON [info] r5kukRMmZNI: Downloading 1 format(s): 313 [dashsegments] Total fragments: 37 [download] Destination: 6.webm [download] 100% of 366.66MiB in 00:00:27 at 13.54MiB/s
> > 
> > 
> > 可以考虑在下面的测试结果里标一下那一部分是tuic，那一部分是hy
> 
> 没必要吧，人家已经写了 hy 1.3.4 （1078端口）vs tuic1.0.0-beta0 （1080端口）。

你是对的。。我看错了。。
