### ISSUE TITLE
请问一个客户端能否连接多个服务端？

### ISSUE THREAD

**Issue by gray0128** [EAimTY/tuic#163]
当有多个服务端时，一个客户端能否连接多个服务端？如果可以配置文件如何书写？

**Comment by molezz** [comment]
我是启动了2个进程

**Comment by gray0128** [comment]
> 

请问如何启动两个进程？不同进程对应不同的配置文件？

**Comment by molezz** [comment]
> > 
> 
> 请问如何启动两个进程？不同进程对应不同的配置文件？

对 2个文件
