### ISSUE TITLE
是否支持alpinelinux？还是我配置错误

### ISSUE THREAD

**Issue by brick2008** [EAimTY/tuic#165]
alpinelinux edge
tuic-server-1.0.0-pre-alpha0

{
        "server": "[::]:443",
        "users": {"be998b07-ee5e-4c34-aa8d-2b2baad5b428": "xxxxxxxxxxxx"},
        "certificate": "/etc/tuic/cert.pem",
        "private_key": "/etc/tuic/cert.key",
        "congestion_control": "bbr",
        "alpn": ["h3", "spdy/3.1"],
        "udp_relay_ipv6": true,
        "zero_rtt_handshake": false,
        "dual_stack": true,
        "auth_timeout": "3s",
        "max_idle_time": "10s",
        "max_external_packet_size": 1500,
        "gc_interval": "3s",
        "gc_lifetime": "15s",
        "log_level": "warn"
}

提示Invalid argument (os error 22)，是我配置错了还是不支持alpine？另外问下certificate和key怎么生成？

**Comment by EAimTY** [comment]
`Invalid argument (os error 22)` 错误见 https://github.com/EAimTY/tuic/issues/164#issuecomment-1562930237

cert 与 key 可以使用 rcgen 自签生成，或者使用 letsencrypt 生成。

**Comment by onenora** [comment]
抱歉，借楼，是否可以自定义log到文件中，类似/var/log/error.log和/var/log/access.log,现在只会在终端看log，比较难翻。

**Comment by EAimTY** [comment]
> 抱歉，借楼，是否可以自定义log到文件中，类似/var/log/tuic/error.log和/var/log/tuic/access.log,现在只会在终端看log，比较难翻。

#111
