### ISSUE TITLE
panicked, client and server at same time

### ISSUE THREAD

**Issue by wen-long** [EAimTY/tuic#173]
run with RUST_BACKTRACE=full

client tuic-client-1.0.0-alpha1-aarch64-apple-darwin
```
' panicked at 'called `Result::unwrap()` on an `Err` value: ExportKeyingMaterialError', tuic-quinn/src/lib.rs:548:14
stack backtrace:
   0:        0x104a66894 - __mh_execute_header
   1:        0x1049af3ac - __mh_execute_header
   2:        0x104a49c7c - __mh_execute_header
   3:        0x104a69d50 - __mh_execute_header
   4:        0x104a69a3c - __mh_execute_header
   5:        0x104a6aa8c - __mh_execute_header
   6:        0x104a6a538 - __mh_execute_header
   7:        0x104a6a4ac - __mh_execute_header
   8:        0x104a6a4a0 - __mh_execute_header
   9:        0x104abba74 - __mh_execute_header
  10:        0x104abbd90 - __mh_execute_header
  11:        0x104aa1c50 - __mh_execute_header
  12:        0x104aa062c - __mh_execute_header
  13:        0x104a748e8 - __mh_execute_header
  14:        0x104a778b8 - __mh_execute_header
  15:        0x104a6e4fc - __mh_execute_header
  16:        0x104a6e30c - __mh_execute_header
  17:        0x104a6b5ac - __mh_execute_header
  18:        0x18096106c - __pthread_deallocate

```

server tuic-server-1.0.0-alpha1-x86_64-unknown-linux-musl
```
thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code', /project/tuic-server/src/connection/mod.rs:122:79
stack backtrace:
   0:     0x7fd0a39df6ce - <unknown>
   1:     0x7fd0a38fae4f - <unknown>
   2:     0x7fd0a39bac56 - <unknown>
   3:     0x7fd0a39e127f - <unknown>
   4:     0x7fd0a39e0980 - <unknown>
   5:     0x7fd0a39e1b17 - <unknown>
   6:     0x7fd0a39e14e3 - <unknown>
   7:     0x7fd0a39e1476 - <unknown>
   8:     0x7fd0a39e1461 - <unknown>
   9:     0x7fd0a38b5732 - <unknown>
  10:     0x7fd0a38b5902 - <unknown>
  11:     0x7fd0a38c9eea - <unknown>
  12:     0x7fd0a38e4da6 - <unknown>
  13:     0x7fd0a39eb148 - <unknown>
  14:     0x7fd0a39ee84c - <unknown>
  15:     0x7fd0a39e51c4 - <unknown>
  16:     0x7fd0a39e4f95 - <unknown>
  17:     0x7fd0a39e2455 - <unknown>
Aborted (core dumped)
```

如何排查呢？可否提供含调试信息的二进制

**Comment by EAimTY** [comment]
你所设置的 password 长度是多少？太短的 password 可能导致了这个问题

**Comment by wen-long** [comment]
2个字符，是生成的，类似 56Q9LK03W8yQ0RwNTobB

**Comment by EAimTY** [comment]
我测试了一些类似你给出的密码，但没能复现这个问题。
如果你的密码是随机生成的且不重要，可以替代，能否提供出现问题密码？
在项目目录内使用 cargo build 可以得到含调试信息的二进制文件。

**Comment by wen-long** [comment]
是 6Sj9v0CgByzlRtf9N58F
顺便一提，我的场景有不少连接是到 server 本身的，也就是通过 tuic server 访问 tuic server 所在机器的其他服务，不知道有没有影响
好的，我编译下再试试

**Comment by brick2008** [comment]
有同样错误，发生在win11，用yt-dlp通过socks5第二次下载youtube视频时

版本：[tuic-client-1.0.0-beta0]

C:\Users\Administrator>t -c 0.json
[2023-05-31T05:01:37Z WARN ] [socks5] server started, listening on [::]:1080
[2023-05-31T05:03:19Z WARN ] [relay] connection error: timed out
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ExportKeyingMaterialError', tuic-quinn\src\lib.rs:548:14
stack backtrace:
   0:     0x7ff75f618f23 - <unknown>
   1:     0x7ff75f54e37b - <unknown>
   2:     0x7ff75f60d2b9 - <unknown>
   3:     0x7ff75f61aeeb - <unknown>
   4:     0x7ff75f61acb9 - <unknown>
   5:     0x7ff75f61ba0b - <unknown>
   6:     0x7ff75f61b4b5 - <unknown>
   7:     0x7ff75f61b409 - <unknown>
   8:     0x7ff75f61b3f4 - <unknown>
   9:     0x7ff75f68fa65 - <unknown>
  10:     0x7ff75f68ff83 - <unknown>
  11:     0x7ff75f65be09 - <unknown>
  12:     0x7ff75f65a632 - <unknown>
  13:     0x7ff75f6256a3 - <unknown>
  14:     0x7ff75f62929d - <unknown>
  15:     0x7ff75f61ede6 - <unknown>
  16:     0x7ff75f61ebcd - <unknown>
  17:     0x7ff75f61828c - <unknown>
  18:     0x7fff8ca926ad - BaseThreadInitThunk
  19:     0x7fff8e18a9f8 - RtlUserThreadStart

**Comment by nasaboy** [comment]
server要是sni的域名，可以在下面单独添加"ip":

**Comment by EAimTY** [comment]
> 这样的格式提示不对，改为绑定ipv6地址的域名没问题

IP 可以作为证书 Common Name（也就是 SNI）被填入 `server` 字段的 hostname 中，但目前 config 在 deserialize server name 的时候分割 hostname 与 port 的逻辑存在问题，导致 IPv6 地址中的冒号被当作分隔符。这个问题会在下个版本中修复

**Comment by EAimTY** [comment]
我仍然没有复现 client 在 ExportKeyingMaterial 时 panic 的问题。请提供完整的 server 与 client config，特别是其中 zero-rtt-handshake 的设置。

[当 QUIC connection 没有完成握手时，export keying material 不会成功](https://docs.rs/rustls/latest/rustls/quic/enum.Connection.html#method.export_keying_material)，因此我怀疑是握手完成前使用 ExportKeyingMaterial 的问题

**Comment by EAimTY** [comment]
server 崩溃是由于 client 在完成握手前就崩溃了，这个问题已经在 056f880a29b5c4af9dfc8d875a2f970e33256b84 被修复

**Comment by wen-long** [comment]
配置除了
```
        "zero_rtt_handshake": true,
        "alpn": ["h3"]
```
都是最小必要参数，uuid 是 11111111-1111-1111-1111-111111111111
服务端也开启了 zero_rtt_handshake


我试了下，服务端关闭好像会导致客户端循环 panic 不能恢复，有可能当时观察到的现象与服务端崩溃或者手动重启有关

**Comment by EAimTY** [comment]
我推测客户端关闭 `zero_rtt_handshake` 后就不会再 panic。如果这个推测正确，那问题大概就在未完成握手的连接 export key material

**Comment by wen-long** [comment]
试了下客户端关闭 `zero_rtt_handshake` 时服务端重启，客户端确实没有发生 panic

**Comment by EAimTY** [comment]
如果推测是正确的，这个问题应该在 d9f089d51ada0f11c971b7a36748b01e5e9479e5 被解决了，client 会在连接彻底建立后 export keying material。

server 与 client 的修复都已被包含在新版本 `1.0.0-rc0` 中。

**Comment by wen-long** [comment]
1.0.0-rc0 测试，服务端重启后客户端没有 panic
