### ISSUE TITLE
Android GUI 下游适配疑问

### ISSUE THREAD

**Issue by arm64v8a** [EAimTY/tuic#176]
https://github.com/MatsuriDayo/NekoBoxForAndroid

1. 协议版本在 UI 上如何区分？之前的叫 v4 现在叫 v5？还是 v0 和 v1？
2. 目前 `aarch64-unknown-linux-musl` 能在 Android 平台运行，但无法解析服务器域名（这可能与 go Android 非 cgo 编译版本无法解析 DNS 是同一类问题）我尝试过用 ndk 构建，也不行，请问有计划修复吗？
3. Android 构建有两个主要的补丁， https://github.com/MatsuriDayo/tuic/commit/329dab2c360d6d5f88ca6e5907016c7b1ea98dea https://github.com/MatsuriDayo/tuic/commit/aca2d7d5bac684edd63987113e584f2b611fa68c 如果可以合并到上游，就可以直接使用上游发布的 binary 做插件了，这样会方便一些，请问是否接受这种 PR ？（不影响其他平台）
4. 是否有计划提供 allow_insecure 选项？

**Comment by EAimTY** [comment]
> 协议版本在 UI 上如何区分？之前的叫 v4 现在叫 v5？还是 v0 和 v1？

> 目前打算 协议版本选择 写 v4 和 v5，新的插件名字叫 tuic-v1 ，因为新版本 tuic-client 不兼容之前的协议了，不能直接取代。

我认为插件名应该使用协议本身的版本而不是其实现的版本，所以称之为 v5 可能更好一些。

> 目前 aarch64-unknown-linux-musl 能在 Android 平台运行，但无法解析服务器域名（这可能与 go Android 非 cgo 编译版本无法解析 DNS 是同一类问题）我尝试过用 ndk 构建，也不行，请问有计划修复吗？

这里的 TUIC client 实现为了保持简单，底层直接调用了 libc 的 DNS 解析，因此这个问题可能是 libc 兼容性导致的。[cross](https://github.com/cross-rs/cross) 可以自动调用 ndk 并编译至 `aarch64-linux-android` / `armv7-linux-androideabi`，理论上能够解决这个问题。

> Android 构建有两个主要的补丁， https://github.com/MatsuriDayo/tuic/commit/329dab2c360d6d5f88ca6e5907016c7b1ea98dea https://github.com/MatsuriDayo/tuic/commit/aca2d7d5bac684edd63987113e584f2b611fa68c 如果可以合并到上游，就可以直接使用上游发布的 binary 做插件了，这样会方便一些，请问是否接受这种 PR ？（不影响其他平台）

由于这里的实现只是参考性质的，为了保持简单，不应该加入任何 platform-specified 代码。

> 是否有计划提供 allow_insecure 选项

目前没有计划，理由同上
