### ISSUE TITLE
优化多IP地址服务器监听

### ISSUE THREAD

**Issue by Fhokud** [EAimTY/tuic#178]
```json
        "server": ["IPv4(1):443", "IPv6(1):443", "IPv6(2):443" ]
```

当服务器拥有大量IP地址时，希望可以指定监听部分IP，而不是监听 所有 或 某一个

**Comment by EAimTY** [comment]
> 当服务器拥有大量IP地址时，希望可以指定监听部分IP，而不是监听 所有 或 某一个

对于一个 socket，只能 bind 一个 IP 地址或者 unspecified，如果需要同时监听多个 IP 就需要建立多个 socket，可以启动多个 TUIC 进程各自监听一个 IP。

> 还有就是需要监听ipv6 :: 而不监听ipv4的情况

server 绑定 `[::]` 并关闭 dual-stack socket 就是只监听 IPv6

**Comment by Zxis233** [comment]
> > 当服务器拥有大量IP地址时，希望可以指定监听部分IP，而不是监听 所有 或 某一个
> 
> 对于一个 socket，只能 bind 一个 IP 地址或者 unspecified，如果需要同时监听多个 IP 就需要建立多个 socket，可以启动多个 TUIC 进程各自监听一个 IP。
> 
> > 还有就是需要监听ipv6 :: 而不监听ipv4的情况
> 
> server 绑定 `[::]` 并关闭 dual-stack socket 就是只监听 IPv6

请问如何关闭dual-stack socket呢
