### ISSUE TITLE
No outbound or routing options for tuic-server?

### ISSUE THREAD

**Issue by showgood163** [EAimTY/tuic#180]
There is neither outbound nor routing options for tuic-server v1.0.0.

Maybe add a socks5 outbound on the server side to provide the minimal routing functionality, e.g., `geoip:cn`?

**Comment by chika0801** [comment]
The author's design philosophy is this. The rest of the work needs to be solved by the user. I solved it by opening TUN mode with sing-box. You can refer to https://github.com/chika0801/tuic-install#%E7%94%B1-sing-box-%E6%8F%90%E4%BE%9B-tun-%E6%A8%A1%E5%BC%8F%E9%80%8F%E6%98%8E%E4% BB%A3%E7%90%86v2rayn-%E7%AE%A1%E7%90%86%E9%85%8D%E7%BD%AE

**Comment by showgood163** [comment]
> The author's design philosophy is this. The rest of the work needs to be solved by the user. I solved it by opening TUN mode with sing-box. You can refer to [here](https://github.com/chika0801/tuic-install#%E5%AE%A2%E6%88%B7%E7%AB%AF).

I think the link you provided do not solve the problem of the routing on the **server** side.

**Comment by chika0801** [comment]
> > The author's design philosophy is this. The rest of the work needs to be solved by the user. I solved it by opening TUN mode with sing-box. You can refer to [here](https://github.com/chika0801/tuic-install#%E5%AE%A2%E6%88%B7%E7%AB%AF).
> 
> I think the link you provided doesn't solve the routing problem on the **server** side.

Sorry, I read your title you are asking about the server side. tuic is not this function. The author's intention is also to keep it as simple as possible, and the rest the user has to operate on his own.

**Comment by chika0801** [comment]
You can switch to a different way of thinking, you do a good CN IP shunt on the client side, you don't need to handle it on the server side.

**Comment by showgood163** [comment]
> You can switch to a different way of thinking, you do a good CN IP shunt on the client side, you don't need to handle it on the server side.

What I want to do on the server side is using warp or any other methods to access contents in `geoip:cn` and `geosite:cn` while accessing other contents directly.

**Comment by showgood163** [comment]
> See https://github.com/EAimTY/tuic/tree/dev/tuic-server#overview

OK. I got that.

**Comment by chika0801** [comment]
I suddenly have an idea that you use sing-box to open TUN, sing-box inside support wireguard outbound, and the diversion function.

https://github.com/SagerNet/sing-box/commit/6a0acf10526e4e5a7c2eb40ed9435838635a1498#diff-97277d5598d980f6495250901080d14c6b4762319fa88bc75c441b3e1c2101b6

**Comment by showgood163** [comment]
> I suddenly have an idea that you use sing-box to open TUN, sing-box inside support wireguard outbound, and the diversion function.
> 
> [SagerNet/sing-box@6a0acf1#diff-97277d5598d980f6495250901080d14c6b4762319fa88bc75c441b3e1c2101b6](https://github.com/SagerNet/sing-box/commit/6a0acf10526e4e5a7c2eb40ed9435838635a1498#diff-97277d5598d980f6495250901080d14c6b4762319fa88bc75c441b3e1c2101b6)

Does the sing-box support the TUIC 1.0.0? The latest release of sing-box is like 4 days ago.

**Comment by chika0801** [comment]
I don't know about this, you can go to the sing-box telegram group and ask the author about it.

**Comment by showgood163** [comment]
> I don't know about this, you can go to the sing-box telegram group and ask the author about it.

OK, I will try this.

**Comment by showgood163** [comment]
> I suddenly have an idea that you use sing-box to open TUN, sing-box inside support wireguard outbound, and the diversion function.
> 
> [SagerNet/sing-box@6a0acf1#diff-97277d5598d980f6495250901080d14c6b4762319fa88bc75c441b3e1c2101b6](https://github.com/SagerNet/sing-box/commit/6a0acf10526e4e5a7c2eb40ed9435838635a1498#diff-97277d5598d980f6495250901080d14c6b4762319fa88bc75c441b3e1c2101b6)

Use TUN inbound as a global proxy? Can you elaborate on your idea?

**Comment by n1arash** [comment]
@showgood163 did you find a way to redirect traffic to WARP in server?

**Comment by showgood163** [comment]
> @showgood163 did you find a way to redirect traffic to WARP in server?

No, at least for now.
