### ISSUE TITLE
TCP stream relaying error: sending stopped by peer: error 0

### ISSUE THREAD

**Issue by yonggekkk** [EAimTY/tuic#183]
一切正常，但V2rayN日志一直刷这个。。问题大吗？

**Comment by yonggekkk** [comment]
TCP stream relaying error: 你的主机中的软件中止了一个已建立的连接。 (os error 10053)

**Comment by EAimTY** [comment]
如果使用正常，那这个问题应该是你的 socks5 client 导致的。
如果 socks5 client 没有通过正常的“发送 EOF 并挥手”流程结束 TCP 连接，TUIC client 的 socks5 server 就会报这个错误

**Comment by 18o** [comment]
同样的问题，clash socks5 client 连接 TUIC client 的 socks5 server 也遇到了。

**Comment by leewi9** [comment]
> 同样的问题，clash socks5 client 连接 TUIC client 的 socks5 server 也遇到了。

请问有什么解决办法吗？
