### ISSUE TITLE
在API接口无法查询到client的下载地址

### ISSUE THREAD

**Issue by AmberisMyShiba** [EAimTY/tuic#185]
0.8.5之前的版本可以在api接口(https://api.github.com/repos/EAimTy/tuic/releases/latest)
查询到server和client的下载地址。1.0.0版的只能查询到server的下载网址，client的查询不到。

**Comment by EAimTY** [comment]
这个仓库中现在有 4 个 crates，每个 crate 有各自的版本，因此不会在一个 release 中发布
