### ISSUE TITLE
是否能增加端口跳跃功能

### ISSUE THREAD

**Issue by ggrreeeedd** [EAimTY/tuic#195]
udp易被qos，是否可以可以加入

**Comment by newmacuser** [comment]
> udp易被qos，是否可以可以加入

该功能的服务端可以用iptables转发实现吧，不需要额外增加这个功能

**Comment by moranno** [comment]
服务端好实现，用iptables。

只要客户端实现就好了。

**Comment by newmacuser** [comment]
> 服务端好实现，用iptables。
> 
> 只要客户端实现就好了。

我纯小白，猜想客户端如果只是自己用的话，是不是可以简单用crontab写个定时刷新（重载）配置的脚本？比如每十分钟换一个端口。

**Comment by moranno** [comment]
> > 服务端好实现，用iptables。
> > 只要客户端实现就好了。
> 
> 我纯小白，猜想客户端如果只是自己用的话，是不是可以简单用crontab写个定时刷新（重载）配置的脚本？比如每十分钟换一个端口。

虽然可以，但是不优雅...还是等 @EAimTY 改进下客户端实现吧。如果本项目做了，其他客户端项目自然会跟进的。

**Comment by EAimTY** [comment]
<https://github.com/EAimTY/tuic/tree/dev/tuic-client#overview>

欢迎 fork 本项目，实现后贡献给社区

**Comment by Itsusinn** [comment]
https://autumnquiche.github.io/RFC9000_Chinese_Simplified/#9_Connection_Migration

**Comment by Itsusinn** [comment]
https://docs.rs/quinn/latest/quinn/struct.Endpoint.html#method.rebind
