### ISSUE TITLE
[Request] Add bbr2 congestion control

### ISSUE THREAD

**Issue by showgood163** [EAimTY/tuic#196]
Bbr2 is implemented in linux-zen kernel.

See https://github.com/zen-kernel/zen-kernel

**Comment by moranno** [comment]
bb2实际速度会更慢。感觉意义不大。
参见测试：
https://roov.org/2020/03/bbr-bbrplus-bbr2/

**Comment by EAimTY** [comment]
欢迎为上游 [quinn](https://github.com/quinn-rs/quinn) 贡献
