### ISSUE TITLE
arm64client提示free(): invalid pointer

### ISSUE THREAD

**Issue by molezz** [EAimTY/tuic#2]
win10下和x86linux下client正常使用
N1盒子作为客户端armbian，各种参数下提示
```
[2022-03-21T13:10:47Z INFO ] [socks5] started. Listening: 0.0.0.0:2080
free(): invalid pointer
Aborted
```

**Comment by EAimTY** [comment]
为了减小文件体积，release 里的二进制文件都是 strip 并且 panic="abort" 的，因此 panic 提示信息很少。

如果方便的话，请使用这个没有动过 panic handler 的版本拿到详细一些的报错信息。
[tuic-client-0.2.1-aarch64-linux.tar.gz](https://github.com/EAimTY/tuic/files/8321564/tuic-client-0.2.1-aarch64-linux.tar.gz)
如果不放心这个二进制文件，可以将仓库根目录 `Cargo.toml` 中 `strip` 和 `panic` 属性去掉后自行编译一份。

另外希望你可以提供一下你的内核版本和 glibc 版本信息，谢谢

**Comment by molezz** [comment]
好像还是很少信息
```
[2022-03-22T08:01:44Z INFO ] [socks5] started. Listening: 127.0.0.1:3080
munmap_chunk(): invalid pointer
Aborted
```

```
# uname -a
Linux N1bian 5.9.0-arm-64 #20.10 SMP PREEMPT Wed Oct 14 12:04:42 MSK 2020 aarch64 aarch64 aarch64 GNU/Linux

 ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.7) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by EAimTY** [comment]
请试试新的 `tuic-server-0.2.2-aarch64-linux-musl`，看问题是否还在

**Comment by molezz** [comment]
tuic-client-0.2.2-aarch64-linux-musl 使用正常
