### ISSUE TITLE
版本号输出有些特别？

### ISSUE THREAD

**Issue by 70599** [EAimTY/tuic#20]
不能用`grep`判断版本号（下例期待返回`tuic is up-to-date.`）
```shell
# latest_ver=0.2.3
# tuic-client -v | grep -q $latest_ver && echo "tuic is up-to-date."
0.2.3
```

版本号也不能输出到文件（下例中`/tmp/test`文件空白）
```shell
# tuic-client -v > /tmp/test
0.2.3
# cat /tmp/test
# 
```

**Comment by EAimTY** [comment]
版本号和帮助信息都被输出到了 stderr，用 `tuic-client -v 2> ver` 可以正常得到结果。
不过这确实有点逻辑问题，所以在 772bd7a9756b6044933c478699382a2538d6177f 之后版本号和帮助信息会输出到 stdout，下一个版本 `0.3.0` 就可以正常使用 `grep` 了。

**Comment by 70599** [comment]
已测试`0.3.0`可用`grep`判断版本号。
