### ISSUE TITLE
TUIC在证书更新后会自动重载么，还是要手动重启TUIC

### ISSUE THREAD

**Issue by Bformax** [EAimTY/tuic#200]
我的证书是由Caddy申请的，想知道证书自动更新以后，
TUIC的默认操作是什么？
是无需干预就可以自动重载证书，还是需要我定时重启TUIC？

**Comment by EAimTY** [comment]
证书在程序启动时加载，不会自动重载

**Comment by Bformax** [comment]
那我设个crontab自动重启一下服务就行
