### ISSUE TITLE
求助：Failed to parse the config file: unknown field `uuid`, expected one of `server`, `port`, `token`, `ip`, `certificates`, `udp_relay_mode`, `congestion_controller`, `heartbeat_interval`, `alpn`, `disable_sni`, `reduce_rtt`, `request_timeout`, `max_udp_relay_packet_size` at line 4 column 15

### ISSUE THREAD

**Issue by Hearing-Loss** [EAimTY/tuic#201]
看起来跟config.json有关但是弄了半天没有找到是什么问题

{
    "relay": {
        "server": "abc.com:58967",
        "uuid": "59143c17-8686-4852-86cd-ef35a1c0a518",
        "password": "bc2bdf",
        "ip": "1.1.1.1",
        "congestion_control": "bbr",
        "alpn": ["h3", "spdy/3.1"]
    },
    "local": {
        "server": "127.0.0.1:55555"
    },
    "log_level": "info"
}

**Comment by EAimTY** [comment]
你的 binary 是旧版本但 config 是新版本的

**Comment by Hearing-Loss** [comment]
> 你的 binary 是旧版本但 config 是新版本的

啊？可我下载的是release里的tuic-client-1.0.0-x86_64-pc-windows-msvc.exe 好像就是最近release的

**Comment by EAimTY** [comment]
`token` 与 `reduce_rtt` 两项设置都仅存在于旧版本中，所以一定是你在旧版本客户端中使用了新版的配置文件

**Comment by Hearing-Loss** [comment]
找到原因了，原来是因为V2ray自己有自带Tuic的客户端，它是旧版本的。所以没有应用从Github上面下载的新客户端，要把新客户端执行文件覆盖到V2ray的bin\tuic文件夹
