### ISSUE TITLE
vir服务器不能用？

### ISSUE THREAD

**Issue by shaojs321** [EAimTY/tuic#206]
有人使用vir试过吗，tuic好像用不了，我用的mack-a八合一脚本，vless能用,电脑v2rayn6.2.7版本
客户端配置
{
    "relay": {
        "server": "XXX:27364",
        "uuid": "0a024f54-f095-4e00-93bc-29b0467a0b83",
        "password": "0a01bf54-f095-4e00-93bc-29b0467a0b83",
        "ip": "XXX",
        "congestion_control": "bbr",
        "alpn": ["h3"]
    },
    "local": {
        "server": "127.0.0.1:7798"
    },
    "log_level": "warn"
}

**Comment by chika0801** [comment]
virmach东京，我测试了，可以用
