### ISSUE TITLE
启用客户端的--enable-ipv6选项无法连接的问题

### ISSUE THREAD

**Issue by kckm** [EAimTY/tuic#21]
windows x64，代理应用填写127.0.0.1，日志：
`[2022-04-06T09:21:07Z ERROR] [relay] [connection] timed out`

代理应用填写 ::1依旧不通
`[2022-04-06T09:24:37Z INFO ] [socks5] started. Listening: [::1]:1080`
`[2022-04-06T09:24:39Z DEBUG] [socks5] [[::1]:65035] [establish]`
`[2022-04-06T09:24:39Z DEBUG] [socks5] [[::1]:65035] [handshake]`
`[2022-04-06T09:24:39Z INFO ] [socks5] [[::1]:65035] [connect] [www.gstatic.com:80]`

**Comment by EAimTY** [comment]
新版本应该解决了问题

**Comment by kckm** [comment]
> 新版本应该解决了问题

一样的问题，--local-ip设置为`::1`，代理应用无论接入`127.0.0.1`还是`::1`都不通。

**Comment by EAimTY** [comment]
> 一样的问题，--local-ip设置为`::1`，代理应用无论接入`127.0.0.1`还是`::1`都不通。

`127.0.0.1` map 到 IPv6 后是 `::ffff:127.0.0.1`，`::1` 无法监听到是正常的。
我这边无法复现 `::1` 的问题，测试 `::1` 可以连通。另外我觉得本地 socks5 使用 IPv6 意义不大，请问是有什么特殊需求吗？

**Comment by kckm** [comment]
用shaowsocks监听本地`::1`是可以用clash连接的，tuic监听`::1`则不行。
没有这个需求，仅仅是测试。
服务端监听ipv6地址这个功能对我来说更有用。
