### ISSUE TITLE
server端请求添加socks5出站

### ISSUE THREAD

**Issue by iambaolong** [EAimTY/tuic#223]
这样分流就更方便啦

**Comment by KoinuDayo** [comment]
你可以把tuic当隧道然后在里面套个TFO的裸TCP

**Comment by showgood163** [comment]
> 你可以把tuic当隧道然后在里面套个TFO的裸TCP [XTLS/Xray-core#1844 (comment)](https://github.com/XTLS/Xray-core/issues/1844#issuecomment-1642049581)

套一层的做法在手机上部署有些麻烦啊

**Comment by neweva** [comment]
sing-box 最新 dev-next 已經支持tuic
