### ISSUE TITLE
运行一段时间后连接不上

### ISSUE THREAD

**Issue by ConnersHua** [EAimTY/tuic#228]
症状为服务端运行一段时间后客户端连接不上，使用 `systemctl status tuic` 命令查看服务状态为 `active (running)`，近期日志伴随大量的 `failed to create UDP associate IPv4 socket: Too many open files (os error 24)`

在使用 `systemctl restart tuic` 重启后正常，症状有时一天好几次，有时好几天一次

配置文件为
```json
{
    "server": "0.0.0.0:8443",
    "users": {
        "uuid": "password"
    },
    "certificate": "/usr/local/etc/tuic/fullchain.pem",
    "private_key": "/usr/local/etc/tuic/private.key",
    "congestion_control": "bbr",
    "alpn": ["h3"],
    "zero_rtt_handshake": false,
    "auth_timeout": "3s",
    "max_idle_time": "10s",
    "max_external_packet_size": 1500,
    "gc_interval": "3s",
    "gc_lifetime": "15s",
    "log_level": "warn"
}
```

[journal.log](https://github.com/EAimTY/tuic/files/12158229/journal.log)

**Comment by qiumzh** [comment]
udp 阻断严重

**Comment by kilvn** [comment]
确定不先看一下 maxopenfiles 参数配置合理性吗

**Comment by mieqq** [comment]
同样出现过，gnu 版本，max openfiles 为 1024，升级 Debian 12 后没怎么出现了

**Comment by kilvn** [comment]
> 同样出现过，gnu 版本，max openfiles 为 1024，升级 Debian 12 后没怎么出现了

1024 肯定不行啊，不出问题就坏了。最低都得 65535，自己了解下

**Comment by mieqq** [comment]
> > 同样出现过，gnu 版本，max openfiles 为 1024，升级 Debian 12 后没怎么出现了
> 
> 1024 肯定不行啊，不出问题就怪了。最低都得 65535，自己了解下这个参数

默认就是这样，其他协议也从来没出过问题，甚至 Tuic V5 以前也没出现

**Comment by wanlce** [comment]
一般服务器的 ulimit -n 限制都是 1024 
如 https://github.com/EAimTY/tuic/issues/211 问题描述，tuic-server 的 UDP socket  的数量会一直增长，最终到达限制，无法再新建连接。
![image](https://github.com/EAimTY/tuic/assets/55907021/b68525ea-3412-4061-9010-5239cbe9fb06)
上面 Grafana 图表显示的是达到默认nofile 1k 限制后，修改nofile并重新运行后，tuic的UDP socket增长过程。

使用以下命令来统计 tuic 相关的 UDP socket 数量
 ` ss -npul | grep tuic | wc -l`

**Comment by ConnersHua** [comment]
感谢各位
