### ISSUE TITLE
[Q] How to use tuic on android?

### ISSUE THREAD

**Issue by showgood163** [EAimTY/tuic#23]
I didn't see any .apk files in the release section for android.
Could you put up a tutorial on how to use tuic on android?

**Comment by EAimTY** [comment]
Files in the release section are executable binaries. You can use them on Android inside a terminal emulator, but in fact they are mainly for client developers and tests. Currently the best way for users to use tuic is to run it on the router.

**Comment by showgood163** [comment]
Got it.
