### ISSUE TITLE
可以推出官方的tuic全平台客户端吗

### ISSUE THREAD

**Issue by do02fw** [EAimTY/tuic#231]
可以推出官方的tuic全平台客户端吗，目前市面上的客户端乱七八糟，不统一，而且有的还需要插件什么的，还不支持全局模式（代理所有流量（tcp udp icmp等）

**Comment by do02fw** [comment]
> 推荐sing-box

唱歌盒子电脑用不了，没有界面，也没有教程

**Comment by chika0801** [comment]
> > 推荐sing-box
> 
> 唱歌盒子电脑用不了，没有界面，也没有教程

教程这有 https://github.com/chika0801/sing-box-examples/tree/main/Tun
