### ISSUE TITLE
在v5 1.0.0版本中，怎么在服务端设置只使用ipv4,不要使用ipv6

### ISSUE THREAD

**Issue by flyhigao** [EAimTY/tuic#233]
我有台服务器，ipv4可以看netflix，ipv6就不行。 可是我看到tuic在同时使用ipv4和ipv6进行netflix的连接：
![image](https://github.com/EAimTY/tuic/assets/47943621/be8050d6-2be1-452f-a737-b57306d1ce8f)

我在sever上已经修改gai.conf使得ipv4的优先度更高了，可是还是一样如上。
我找不到有什么配置可以让tuic仅仅使用ipv4，我要怎么设置呢？

**Comment by EAimTY** [comment]
listen 0.0.0.0

**Comment by flyhigao** [comment]
> listen 0.0.0.0

不行。这个仅仅是监听的改变，可是tuic仍然会从ipv6的出口去访问外网
![image](https://github.com/EAimTY/tuic/assets/47943621/380f05c4-51cb-4875-8015-1fd1ed60ef05)

**Comment by EAimTY** [comment]
连接 outbound 时会直接使用 libc 提供的 `getaddrinfo()`。可以试试在设置 gai.conf 的同时修改 resolv.conf，删除 `options inet6`，添加 `options single-request`。或者可以尝试用一些工具劫持系统的 DNS

**Comment by flyhigao** [comment]
hysteria有个配置，是
"resolve_preference": "46"  就是dns解析，v4优先v6，如果设为4,就是仅仅返回v4的地址。
tuic也能有类似的吗？

**Comment by flyhigao** [comment]
> 连接 outbound 时会直接使用 libc 提供的 `getaddrinfo()`。可以试试在设置 gai.conf 的同时修改 resolv.conf，删除 `options inet6`，添加 `options single-request`。或者可以尝试用一些工具劫持系统的 DNS

我的场景，解释一下：
我的server上有x-ui，已经设置好vmess+ws的ipv4和v6的路由分流。运行正常。所以我不能修改系统的dns的优先度。
tuic的0-RTT 非常好，用来玩游戏非常棒，但现在ipv6的延迟很大，而且有使用上的限制， 所以如果tuic能指定ipv4或v6就好了。

**Comment by flyhigao** [comment]
gpt的回答：
即使你在 /etc/gai.conf 中调整了优先级，getaddrinfo() 仍然可能会返回 IPv4 和 IPv6 地址，因为这个函数是用来执行通用的地址解析操作，不会受到 gai.conf 的影响。getaddrinfo() 函数根据系统网络配置以及目标主机的 DNS 记录来返回可能的地址列表。

gai.conf 中的设置主要影响的是在某些情况下，例如主机名解析，系统会尝试选择哪种地址类型。但在某些应用程序中，特别是涉及网络通信的程序中，getaddrinfo() 会返回所有可用的地址，而不仅限于 gai.conf 中指定的地址优先级。

如果你希望在你的程序中只返回 IPv4 地址，你可能需要在代码中显式筛选出 IPv4 地址。这可以通过检查返回的地址列表并过滤掉 IPv6 地址来实现。注意，这样做可能需要一些额外的编程工作。

**Comment by flyhigao** [comment]
换了
