### ISSUE TITLE
请教下关于中转的问题

### ISSUE THREAD

**Issue by humbass** [EAimTY/tuic#235]
刚用上 tuic 1.0.0 版本，尝试使用端口中转工具在国内的服务器部署一个中转，没有成功，请教是否支持类似的操作？

背景是：一个办公室有几个人同时在使用，就想能不能隐蔽一些，通过一台服务器来中转流量。

**Comment by YongChingShieh** [comment]
完全是可以的 我就是这样做  一台pc 在路由器里面设置固定ip 设置端口为10080 ( "server": "127.0.0.1:10080")并且开放防火墙端口
这样其他的局域网设备就可以连接了  如果是公网ip 也一样
