### ISSUE TITLE
支持 TCP 协议作为代理链接

### ISSUE THREAD

**Issue by ghost** [EAimTY/tuic#240]
从 https://github.com/v2fly/v2ray-core/discussions/2687 找过来的。

有一些封锁UDP、且不稳定的网络环境，希望能通过tuic提供稳定的链接。tuic的quic UDP包能安全地塞进udp over TCP里么？

**Comment by f4nff** [comment]
塞进去就毫无意义了.
就陷入另外一个死循环了,
就是tcp的拥塞控制.
