### ISSUE TITLE
服务端重启后，客户端也需要重启才能连接

### ISSUE THREAD

**Issue by kckm** [EAimTY/tuic#27]
服务端重启后，客户端似乎就连不上服务端了，需要重启才能恢复。

**Comment by Error996** [comment]
作者bump version了，你俩都下最新的试试？

**Comment by Error996** [comment]
作者bump version了，你俩都下最新的试试？

**Comment by kckm** [comment]
> 作者bump version了，你俩都下最新的试试？

现在就是用的0.4.0版本

**Comment by kckm** [comment]
服务端就一条日志：
`[2022-04-09T13:08:47Z INFO ] Server started. Listening port: 3888`
`[2022-04-09T13:09:06Z DEBUG] [[::ffff:1.2.3.4]:32054] [establish]`

客户端都是这些:
`[2022-04-09T13:09:23Z DEBUG] [socks5] [127.0.0.1:57620] [establish]`
`[2022-04-09T13:09:23Z DEBUG] [socks5] [127.0.0.1:57620] [handshake]`
`[2022-04-09T13:09:23Z INFO ] [socks5] [127.0.0.1:57620] [connect] [www.gstatic.com:80]`
`[2022-04-09T13:09:23Z INFO ] [relay] [task] [connect] [www.gstatic.com:80]`

**Comment by EAimTY** [comment]
服务端重启后，客户端与服务端之间重新建立连接就可以正常进行中继。问题在于，当服务端重启且客户端有正在进行的中继任务时，客户端认为连接仍有效，会尝试发送心跳指令从而阻止达到 max idle time 的 QUIC 连接断开。在应用层没法观测到连接断开。
只要客户端的没有中继任务，到达 max idle time 后连接会自动释放，这时就可以正常建立连接了。
