### ISSUE TITLE
MAX_UDP_PACKET_SIZE指的是tuic直接发送的UDP(quic)的MTU吗？可以设置的最小值是多少？

### ISSUE THREAD

**Issue by CCCAUCHY** [EAimTY/tuic#29]

**Comment by EAimTY** [comment]
客户端的 MAX_UDP_PACKET_SIZE 控制 socks5 收到 UDP 包的最大大小，server 端是从 tuic 连接的 UDP 中转和外部收到的包的最大大小。包的超出部分会被截断。如果需要设置的话，建议设置到小于等于客户端到服务器路径的 MTU。

之后应该会加上自动 MTU 探测。

**Comment by Error996** [comment]
PPPOE拨号的话岂不都是1492?还是MSS的1452?

**Comment by CCCAUCHY** [comment]
> 客户端的 MAX_UDP_PACKET_SIZE 控制 socks5 收到 UDP 包的最大大小，server 端是从 tuic 连接的 UDP 中转和外部收到的包的最大大小。包的超出部分会被截断。如果需要设置的话，建议设置到小于等于客户端到服务器路径的 MTU。
> 
> 之后应该会加上自动 MTU 探测。

本项目不受quic最小MTU的规定影响吗？希望以后能设置固定的MTU，方便配合UDPspeeder的[mode 1](https://github.com/wangyu-/UDPspeeder/wiki/mode%E5%92%8Cmtu%E9%80%89%E9%A1%B9)

**Comment by fengqi** [comment]
> > 客户端的 MAX_UDP_PACKET_SIZE 控制 socks5 收到 UDP 包的最大大小，server 端是从 tuic 连接的 UDP 中转和外部收到的包的最大大小。包的超出部分会被截断。如果需要设置的话，建议设置到小于等于客户端到服务器路径的 MTU。
> > 之后应该会加上自动 MTU 探测。
> 
> 本项目不受quic最小MTU的规定影响吗？希望以后能设置固定的MTU，方便配合UDPspeeder的[mode 1](https://github.com/wangyu-/UDPspeeder/wiki/mode%E5%92%8Cmtu%E9%80%89%E9%A1%B9)

话说有必要串联一个udpspeeder么

**Comment by EAimTY** [comment]
新版本对这部分做了一些更改。

UDP relay mode `Native` 下中继 UDP 包使用 QUIC 的 datagram，因此数据包大小限制完全取决于 datagram 的最大尺寸。新版本会在这种中继模式下自动检测并匹配 max datagram size.

UDP relay mode `Quic` 下中继 UDP 包使用 QUIC 的 stream，因此理论上数据包大小没有任何限制，完全取决于 inbound 侧的接收缓存设置。因此新版本重新添加了选项 `max_udp_relay_packet_size` 来设置这种中继模式下接收缓存的大小。
