### ISSUE TITLE
可以增加socks5 outbund吗？

### ISSUE THREAD

**Issue by delphinuz** [EAimTY/tuic#32]
这样client/server可经过socks5将数据转发出去。

目前hysteria提供server端的socks5 outbound，这样可以对接cloudflared的warp。

请参考以下讯息。

  "socks5_outbound": {
    "server": "55.66.77.88:1080", // SOCKS5 服务器地址
    "user": "user", // SOCKS5 验证用户名
    "password": "password" // SOCKS5 验证密码
  }

[https://github.com/HyNetwork/hysteria/wiki/%E9%AB%98%E7%BA%A7%E7%94%A8%E6%B3%95](url)

**Comment by EAimTY** [comment]
无此打算。
服务器端可使用 https://github.com/NOBLES5E/cproxy 达到同样的效果
