### ISSUE TITLE
[问题请教]客户端怎样设置检验服务器自签证书或certbot签的证书？

### ISSUE THREAD

**Issue by egg1234** [EAimTY/tuic#36]
想请教一下在客户端怎样设置检验服务器自签证书或certbot签的证书？

举例在hysteria协议的客户端是使用《"insecure": false, // 不忽略一切证书错误》这个参数控制检验服务器自签证书或certbot签的证书，那在tuic协议的客户端是怎样的一个机制及参数？

谢谢！

**Comment by EAimTY** [comment]
tuic 使用的是未经修改的 QUIC 连接流程，两端的 TLS 握手成功才能建立连接。

**Comment by egg1234** [comment]
那举例如果服务器使用自签证书，然后客户端没有使用"certificate": "/PATH/TO/CERT",这行参数，那么两端的握手会成功吗？

**Comment by EAimTY** [comment]
> 那举例如果服务器使用自签证书，然后客户端没有使用"certificate": "/PATH/TO/CERT",这行参数，那么两端的握手会成功吗？

会失败

**Comment by egg1234** [comment]
明白了

有一个考虑是如果将来tuic协议真的PR进Sagernet的话，用户服务器端使用自签证书，那客户端Sagernet这边需要把自签证书的cert文件拷贝到手机，使用上相对麻烦一些
