### ISSUE TITLE
[问题请教]在严重拥挤丢包的线路建议使用“cubic，new_reno，bbr”的哪个参数？

### ISSUE THREAD

**Issue by egg1234** [EAimTY/tuic#37]
或者是“cubic，new_reno，bbr”三个参数分别建议用在什么样的线路场景？

谢谢！

**Comment by delphinuz** [comment]
其实我也好奇  UDP relay mode: "native", "quic"，的差别。在运行时好像差不多。

**Comment by EAimTY** [comment]
> 或者是“cubic，new_reno，bbr”三个参数分别建议用在什么样的线路场景？
> 
> 谢谢！

参见 https://en.wikipedia.org/wiki/TCP_congestion_control。注意 tuic 的 bbr 是 v1。

> 其实我也好奇 UDP relay mode: "native", "quic"，的差别。在运行时好像差不多。

README 里已经讲得很清楚了。这是 UDP 的**中继**模式，对 TCP 中继没有影响。
