### ISSUE TITLE
自签证书不能使用

### ISSUE THREAD

**Issue by feng-king** [EAimTY/tuic#40]
自签证书报错,已在客户端配置证书但还是提示：

[2022-04-17T17:22:00Z ERROR] [relay] [connection] the cryptographic handshake failed: error 42: invalid peer certificate contents: invalid peer certificate: UnknownIssuer

**Comment by EAimTY** [comment]
信息太少，至少要给出你自签证书的方式和使用的命令。是否与 #17 症状相同？

**Comment by feng-king** [comment]
> 信息太少，至少要给出你自签证书的方式和使用的命令。是否与 #17 症状相同？

使用cloudflare的边缘证书，openssl的自签证书都提示这个错误。
openssl签证书
openssl genrsa -out *.key 2048
openssl req -new -key *.key -out *.csr
openssl x509 -req -in *.csr -signkey *.key -out *.crt
还尝试过先自签ca，再用ca签证书，也不行。

**Comment by molezz** [comment]
不支持这类证书吧， 要自己生成

**Comment by molezz** [comment]
好像是rcgen生成， 但是默认的不是自己的域名

**Comment by feng-king** [comment]
可以了，需要在客户端配置签发者证书

**Comment by feng-king** [comment]
> 
我现在是使用 https://thiscute.world/posts/about-tls-cert/ 这个里面的ecc证书生成教程。
生成了5个文件，分别是ca.key,ca.pem,server.key,server.csr,server.pem
只需将server.pem与server.key配置到服务端，客户端配置ca.pem即可，我看了一下，你提供网站的证书脚本，应该也可以这样配置，但我没试。还有，我不太喜欢使用disable_sni选项允许不安全证书

**Comment by woodlyer** [comment]
@feng-king  
请问客户端配置ca.pem，指的是操作系统导入ca.pem还是 在tuic的配置中添加对ca.pem的支持？
具体可以说的更清楚一些吗？

**Comment by feng-king** [comment]
@woodlyer 
在Android系统，我安装ca证书但并没有起作用，所以我一般配置在配置文件中。在Windows中，你可以选择在系统中安装你的ca证书，而不需要在配置文件中指明ca，这是可行的（我试过且成功了），当然你也可以在配置文件中指明ca证书，这同样且一定可行。

**Comment by woodlyer** [comment]
@feng-king  thank you very much!
