### ISSUE TITLE
服务器端指定ipv4或ipv6出站

### ISSUE THREAD

**Issue by delphinuz** [EAimTY/tuic#42]
tuic突然无法使用，了解后，原来是服务器端的ipv6出问题了，但ipv4是正常的，但tuic还是无法连出，提一点建议。

1 服务器端可以指定ipv4或ipv6优先。
2 增加debug相关讯息，像这次无法连线，很难由debug讯息看出来。
3 好奇tuic是否有进行dns查询，如果客户端是传送域名？如果有，也可增加dns64(解析后ipv6优先)、dns46(解析后ipv4优先)、dns6(解析后只使用ipv6)或dns4(解析后只使用ipv4)。

**Comment by EAimTY** [comment]
> 服务器端可以指定ipv4或ipv6优先。

服务器端有选项 `--enable-ipv6` 可以开启 IPv6 支持，并且监听的是 dual-stack socket，所以仍可接受 IPv4 连接。

> 增加debug相关讯息，像这次无法连线，很难由debug讯息看出来。

客户端连接服务器超时时会有相应 log

> 好奇tuic是否有进行dns查询，如果客户端是传送域名？如果有，也可增加dns64(解析后ipv6优先)、dns46(解析后ipv4优先)、dns6(解析后只使用ipv6)或dns4(解析后只使用ipv4)

从 TUIC 客户端连接 TUIC 服务器时，如果提供的服务器是域名就会在客户端本地调用 libc 进行 DNS 解析，具体是 IPv4 还是 IPv6 是根据收到回复的顺序决定的。

**Comment by delphinuz** [comment]
> 服务器端有选项 --enable-ipv6 可以开启 IPv6 支持，并且监听的是 dual-stack socket，所以仍可接受 IPv4 连接。
> 从 TUIC 客户端连接 TUIC 服务器时，如果提供的服务器是域名就会在客户端本地调用 libc 进行 DNS 解析，具体是 IPv4 还是 IPv6 是根据收到回复的顺序决定的。

所以目前tuic只能选择ipv4或ipv6连出。

当enable-ipv6=false，而本地dns回覆ip第一个为ipv6，那tuic就无法连出？目前测试一下好像如此。

才会建议可以加个ipv4或ipv6优先(或限制)选择。本地dns回复里，可选择ipv4或ipv6连出。

>客户端连接服务器超时时会有相应 log

这情况不是客户端与服务器问题，是服务器连不出去(开启enable-ipv6，但ipv6不通)。不过有无超时的log，我再确认一下。

**Comment by EAimTY** [comment]
> 当enable-ipv6=false，而本地dns回覆ip第一个为ipv6，那tuic就无法连出？目前测试一下好像如此。

确实有这个问题，看来需要重写一下 dns 的部分
