### ISSUE TITLE
打不开www.google.com

### ISSUE THREAD

**Issue by fbion** [EAimTY/tuic#44]
tuic-server-0.6.0-x86_64-linux-gnu --port 443 --token test --certificate ./certificate.crt --private-key ./privkey.key --congestion-controller bbr --enable-ipv6 --log-level debug

tuic-client-0.6.0-x86_64 --server server.domain --server-port 443 --token test --local-port 1091 --server-ip ip --log-level debug

curl -v --proxy socks5h://127.0.0.1:1091 google.com
*   Trying 127.0.0.1...
* TCP_NODELAY set
* SOCKS5 communication to google.com:80
* SOCKS5 request granted.
* Connected to 127.0.0.1 (127.0.0.1) port 1091 (#0)
> GET / HTTP/1.1
> Host: google.com
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Location: http://www.google.com/
< Content-Type: text/html; charset=UTF-8
< Date: Thu, 28 Apr 2022 02:34:18 GMT
< Expires: Sat, 28 May 2022 02:34:18 GMT
< Cache-Control: public, max-age=2592000
< Server: gws
< Content-Length: 219
< X-XSS-Protection: 0
< X-Frame-Options: SAMEORIGIN

[2022-04-28T02:34:18Z INFO ] [socks5] [127.0.0.1:60935] [connect] [google.com:80]
[2022-04-28T02:34:18Z DEBUG] [relay] [connection] [disconnect]
[2022-04-28T02:34:18Z DEBUG] [relay] [connection] [authentication]
[2022-04-28T02:34:18Z DEBUG] [relay] [connection] [establish]
[2022-04-28T02:34:18Z INFO ] [relay] [task] [connect] [google.com:80]
[2022-04-28T02:34:18Z DEBUG] [relay] [connection] [heartbeat]

但是访问www.google.com就不行了

curl -v --proxy socks5h://127.0.0.1:1091 www.google.com
*   Trying 127.0.0.1...
* TCP_NODELAY set
* SOCKS5 communication to www.google.com:80
* SOCKS5 request granted.
* Connected to 127.0.0.1 (127.0.0.1) port 1091 (#0)
> GET / HTTP/1.1
> Host: www.google.com
> User-Agent: curl/7.64.1
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host 127.0.0.1 left intact
curl: (52) Empty reply from server
* Closing connection 0

服务器上tcpdump抓80 显示请示www.google.com有响应 不知道tuic怎么判断的没有返回数据?
在服务器 curl www.google.com 也正常

**Comment by EAimTY** [comment]
之前的 socks5 server 实现有些问题，理论上已在 0.7.0-beta0 中修复了，请试试新版本还有没有这个问题

**Comment by fbion** [comment]
> 之前的 socks5 server 实现有些问题，理论上已在 0.7.0-beta0 中修复了，请试试新版本还有没有这个问题

稳定了很多
还有
当客户端断网恢复后 能不能自动重连
或者服务端进程重启后

**Comment by EAimTY** [comment]
> 当客户端断网恢复后 能不能自动重连
> 或者服务端进程重启后

目前的实现在理论上已经可以做到这两点，现在的问题主要在客户端 relay 层的超时设计上，下个版本准备重构这一部分。
