### ISSUE TITLE
不同的参数对速度的影响

### ISSUE THREAD

**Issue by fbion** [EAimTY/tuic#45]
tuic-server-0.7.0-beta0-x86_64-linux-gnu --port 8443 --token test --certificate ./certificate.crt --private-key ./privkey.key --congestion-controller bbr --log-level debug

tuic-client-0.7.0-beta0-x86_64- --server xx.net --server-port 8443 --token test --local-port 1099 --server-ip 23.23.23.23 --udp-relay-mode quic --congestion-controller bbr --reduce-rtt --log-level debug

修改了不同的参数 测试了下 最张发现 --udp-relay-mode quic --congestion-controller bbr速度才能跑起来
cubic", "new_reno native 都很慢
这是怎么回事
好像8443比443还快一些

**Comment by EAimTY** [comment]
不知你是通过什么方式“测速”的。如果是走 TCP 的方式，`--udp-relay-mode` 选项不会产生任何影响──如字面所言，这是中继 UDP 包方式的设置。
拥塞控制算法当然会对带宽与延迟有，特别是在有丢包的情况下。参见 https://en.wikipedia.org/wiki/TCP_congestion_control
