### ISSUE TITLE
请求支持iptables redirect模式

### ISSUE THREAD

**Issue by PHCSJC** [EAimTY/tuic#47]
iptables redirect转socks5多了一层，性能肯定会有衰减，请求直接支持redirect模式，redirect模式用的人也非常广泛，非常谢谢！

**Comment by EAimTY** [comment]
[README](https://github.com/EAimTY/tuic#why-tuic-client-doesnt-support-other-inbound--advanced-route-settings) 中明确说明了这类问题

**Comment by PHCSJC** [comment]
其实已经看到了，只是再request一下，也许作者看这个需求还挺多人提的就支持了呢，当然没有也就佛系了
