### ISSUE TITLE
基于这个协议的方案 中转是不是不太合适？

### ISSUE THREAD

**Issue by hinego** [EAimTY/tuic#49]
如果需要A -> B -> C 是不是没有比较好的实现方案？

**Comment by EAimTY** [comment]
> 基于这个协议的方案

不知你提到的“方案”具体指的是什么。

tuic 本身可以看作只是一个协议，这个仓库中的 server 和 client 只是我对该协议的实现。任何人都可以根据协议重新实现 tuic，比如 [stash](https://stash.ws)。

如果指的“方案”是协议本身，我认为这个协议其实很适合做中转——因为中转过程本身会增加握手造成的往返时延，这刚好是 tuic 能够优化的。

如果指的“方案”是我的 server 与 client 实现，确实如你所言。我追求最小化实现，不会在实现内增加太多功能，因此需要借助外部工具。

我这里给出一个可行的暂时性方案：

A --tuic--> [[cproxy](https://github.com/NOBLES5E/cproxy)] B [[ipt2socks](https://github.com/zfl9/ipt2socks)] --tuic--> C

借助 cproxy 和 ipt2socks，可以在中转机 B 上将原本的 tuic server 出口（outbound freedom，如果用 v2ray 的方法命名）再交给 B 上的 tuic client，最终到达 C。

需要注意，目前我的 client 实现还存在一个 bug（#15），对于需要长时间运行的 client 需要额外脚本用来监测和重启。
根据目前的开发计划，在下一个版本中我会完全重写 client 与 server 间连接的管理方式，从而修复上面的 bug 并优化性能。这个版本几乎已经开发完成，最近一段时间就会发布。

下下个版本中，我计划直接将 server 与 client 以 crate 形式发布，暴露 API 以供其他想要在此基础上开发的开发者使用。届时如果社区足够壮大，可能可以看到其它中转方案的出现。

**Comment by EAimTY** [comment]
数据多次加解密确实会影响性能，但如果负载不高，对于现代设备的实际影响应该很小。如果多次加解密造成性能损失确实成为了瓶颈，我觉得可以让中转机只做端口转发，不处理数据包实际内容。

**Comment by yuanyiwei** [comment]
tuic 协议能否像各种 tcp/tls 流一样根据 sni 来进行分流/中转呢，这个功能有点用（

（类似的设计：https://github.com/Shadowsocks-NET/shadowsocks-specs/blob/main/2022-2-shadowsocks-2022-extensible-identity-headers.md#scenarios
