### ISSUE TITLE
tuic-server-0.8.0同时监听IPv4和IPv6

### ISSUE THREAD

**Issue by sky92682** [EAimTY/tuic#53]
在0.8.0中，服务器默认监听IPv4的0.0.0.0，以前的enable-ipv6参数已经不再可用，请问一下如何让服务端同时监听IPv4和IPv6？

**Comment by EAimTY** [comment]
当监听 IP 是 IPv6 时，TUIC 会使用 dual-stack socket。因此，只要将 `ip` 选项设置为 `::` 就可以同时监听 IPv4 和 IPv6

**Comment by sky92682** [comment]
测试有效，谢谢您的解答
