### ISSUE TITLE
客户端警告 [socks5] 

### ISSUE THREAD

**Issue by Fhokud** [EAimTY/tuic#55]
服务器 tuic-server-0.8.1-x86_64-linux-gnu
Ubuntu 22.04 

> {
    "port": 443,
    "token": ["验证"],
    "certificate": "/PATH/TO/CERT",
    "private_key": "/PATH/TO/PRIV_KEY",
    "ip": "0.0.0.0",
    "congestion_controller": "bbr",
    "max_idle_time": 15000,
    "authentication_timeout": 1000,
    "alpn": ["h3"],
    "max_udp_relay_packet_size": 1500,
    "log_level": "off"
}

客户端 tuic-client-0.8.1-aarch64-android
安卓11

> "relay": {
        "server": "域名",
        "port": 443,
        "token": "验证",
        "ip": "IP",
        "udp_relay_mode": "quic",
        "congestion_controller": "bbr",
        "heartbeat_interval": 10000,
        "alpn": ["h3"],
        "disable_sni": false,
        "reduce_rtt": true,
        "request_timeout": 8000,
        "max_udp_relay_packet_size": 1500
    },
    "local": {
        "port": 54336,
        "ip": "127.0.0.1"
    },
    "log_level": "debug"
}

运行一段时间后客户端日志中可见大量如下三条警告
socks由firefox beta-103-beta2 直接发出，开启了代理dns请求。

> WARN ] [socks5] [127.0.0.1:43426] Broken pipe (os error 32)
 WARN ] [socks5] [127.0.0.1:43436] Transport endpoint is not connected (os error 107)
WARN ] [socks5] [127.0.0.1:43456] Connection reset by peer (os error 104)

**Comment by Fhokud** [comment]
补充一个问题
 NatTypeTester测试结果为Symmetric NAT，并不是Readme所说的Full Cone NAT

**Comment by EAimTY** [comment]
> [socks5] [127.0.0.1:43426] Broken pipe (os error 32)
> [socks5] [127.0.0.1:43436] Transport endpoint is not connected (os error 107)
> [socks5] [127.0.0.1:43456] Connection reset by peer (os error 104)

这三条 WARN 应该是 socks5 client 端未按正常流程进行 TCP 挥手导致的，理论上不会影响正常的连接，至少在桌面端如此。出现这些错误时 TCP 连接仍会被正确释放，因此不会产生太大问题。

**Comment by bash99** [comment]
> 补充一个问题 NatTypeTester测试结果为Symmetric NAT，并不是Readme所说的Full Cone NAT 服务器已放高位udp端口

我测试结果的是 Unknown ，也不是 Full Cone NAT，不知道哪儿的错误

**Comment by Fhokud** [comment]
`BUG`

**Comment by YongChingShieh** [comment]
> 服务器 tuic-server-0.8.1-x86_64-linux-gnu Ubuntu 22.04
> 
> > {
> > "port": 443,
> > "token": ["验证"],
> > "certificate": "/PATH/TO/CERT",
> > "private_key": "/PATH/TO/PRIV_KEY",
> > "ip": "0.0.0.0",
> > "congestion_controller": "bbr",
> > "max_idle_time": 15000,
> > "authentication_timeout": 1000,
> > "alpn": ["h3"],
> > "max_udp_relay_packet_size": 1500,
> > "log_level": "off"
> > }
> 
> 客户端 tuic-client-0.8.1-aarch64-android 安卓11
> 
> > "relay": {
> > "server": "域名",
> > "port": 443,
> > "token": "验证",
> > "ip": "IP",
> > "udp_relay_mode": "quic",
> > "congestion_controller": "bbr",
> > "heartbeat_interval": 10000,
> > "alpn": ["h3"],
> > "disable_sni": false,
> > "reduce_rtt": true,
> > "request_timeout": 8000,
> > "max_udp_relay_packet_size": 1500
> > },
> > "local": {
> > "port": 54336,
> > "ip": "127.0.0.1"
> > },
> > "log_level": "debug"
> > }
> 
> 运行一段时间后客户端日志中可见大量如下三条警告 socks由firefox beta-103-beta2 直接发出，开启了代理dns请求。
> 
> > WARN ] [socks5] [127.0.0.1:43426] Broken pipe (os error 32)
> > WARN ] [socks5] [127.0.0.1:43436] Transport endpoint is not connected (os error 107)
> > WARN ] [socks5] [127.0.0.1:43456] Connection reset by peer (os error 104)

这并不是apk文件 话说你是怎么在安卓上运行tuic二进制文件的....

**Comment by Fhokud** [comment]
> 这并不是apk文件 话说你是怎么在安卓上运行tuic二进制文件的....

这里提供一种实现方式。
https://github.com/termux/termux-app

我是通过系统本身的systemd来长期稳定运行tuic二进制文件的。

**Comment by Fhokud** [comment]
> > 服务器 tuic-server-0.8.1-x86_64-linux-gnu Ubuntu 22.04
> > > {
> > > "port": 443,
> > > "token": ["验证"],
> > > "certificate": "/PATH/TO/CERT",
> > > "private_key": "/PATH/TO/PRIV_KEY",
> > > "ip": "0.0.0.0",
> > > "congestion_controller": "bbr",
> > > "max_idle_time": 15000,
> > > "authentication_timeout": 1000,
> > > "alpn": ["h3"],
> > > "max_udp_relay_packet_size": 1500,
> > > "log_level": "off"
> > > }
> > 
> > 
> > 客户端 tuic-client-0.8.1-aarch64-android 安卓11
> > > "relay": {
> > > "server": "域名",
> > > "port": 443,
> > > "token": "验证",
> > > "ip": "IP",
> > > "udp_relay_mode": "quic",
> > > "congestion_controller": "bbr",
> > > "heartbeat_interval": 10000,
> > > "alpn": ["h3"],
> > > "disable_sni": false,
> > > "reduce_rtt": true,
> > > "request_timeout": 8000,
> > > "max_udp_relay_packet_size": 1500
> > > },
> > > "local": {
> > > "port": 54336,
> > > "ip": "127.0.0.1"
> > > },
> > > "log_level": "debug"
> > > }
> > 
> > 
> > 运行一段时间后客户端日志中可见大量如下三条警告 socks由firefox beta-103-beta2 直接发出，开启了代理dns请求。
> > > WARN ] [socks5] [127.0.0.1:43426] Broken pipe (os error 32)
> > > WARN ] [socks5] [127.0.0.1:43436] Transport endpoint is not connected (os error 107)
> > > WARN ] [socks5] [127.0.0.1:43456] Connection reset by peer (os error 104)
> 
> 这并不是apk文件 话说你是怎么在安卓上运行tuic二进制文件的....

这里提供一种实现方式。
https://github.com/termux/termux-app

安卓本就基于Linux这是可以实现的，我是通过系统本身的systemd来长期稳定运行tuic二进制文件的。
