### ISSUE TITLE
client socks5处理ipv6地址时端口出问题

### ISSUE THREAD

**Issue by sT2z** [EAimTY/tuic#56]
client通过socks5访问纯ipv6网址，会改变原有访问地址的端口号，导致不通。

复现：
client通过socks5访问 http://[2606:4700:4700::1111]，
debug显示：

```
[2022-07-07T05:16:40Z DEBUG] [socks5] [127.0.0.1:54798] [establish]
[2022-07-07T05:16:40Z INFO ] [socks5] [127.0.0.1:54798] [connect] [[2606:4700:4700::1111]:20480]
[2022-07-07T05:16:40Z INFO ] [relay] [task] [connect] [[2606:4700:4700::1111]:20480]
```

原本应该是[2606:4700:4700::1111]:80，变成了20480端口。

**Comment by zephyrchien** [comment]
可以复现:

> curl 'http://[2606:4700:4700::1001]' --socks5 127.0.0.1:1080 -vv

[relay] [task] [connect] [[2606:4700:4700::1001]:20480]

> curl 'http://[2606:4700:4700::1001]:81' --socks5 127.0.0.1:1080 -vv

[relay] [task] [connect] [[2606:4700:4700::1001]:20736]

我想应该是字节序的问题:

0x0050 => 80
0x5000 => 20480
0x0051 => 81
0x5100 => 20736

**Comment by EAimTY** [comment]
确实有这个问题，感谢反馈。bug 已经在 [EAimTY/socks5-server - 5578bd5](https://github.com/EAimTY/socks5-server/commit/5578bd5813505b09042302fbf8f619cbbe68e084) 中修复了，TUIC 之后的版本就会包含这个修正。

~看来最好还是要避免手写太多的 unsafe~
