### ISSUE TITLE
非常感谢老大提供的非常优秀的tuic方案

### ISSUE THREAD

**Issue by tianlichunhong** [EAimTY/tuic#59]
希望后续能继续改进。特别是DNS方面。如果能有专门对DNS优化的通道，就更好了。

**Comment by chika0801** [comment]
感谢大佬+1

**Comment by EAimTY** [comment]
各种 DNS 实现在本质上与普通 TCP、UDP 无异。TUIC 协议本身的方案已经足够了，没有必要为 DNS 修改协议。

如果你指的是如“分流”之类的功能，我的这个 TUIC 实现不会添加，[README](https://github.com/EAimTY/tuic#why-tuic-client-doesnt-support-other-inbound--advanced-route-settings) 中已经明确说明了。
