### ISSUE TITLE
udp 转发长度问题

### ISSUE THREAD

**Issue by cute** [EAimTY/tuic#61]
测试 native 模式下直接截断为1147, quic 模式下无响应。
因为 quic 协议的 max_datagram_frame_size 限制，quinn 里大概是 1162。

https://github.com/quinn-rs/quinn/blob/46f9a57d3b274bc84aa34cf69d20a574938fe81f/quinn-proto/src/connection/datagrams.rs#L58

**Comment by cute** [comment]
Hysteria 处理方式是分片

https://github.com/HyNetwork/hysteria/blob/master/pkg/core/protocol.go#L49

**Comment by zephyrchien** [comment]
如果分片的话需要修改协议，工作量还是不少的

**Comment by moranno** [comment]
似乎这个问题已经被修复了：https://github.com/EAimTY/tuic/pull/71
希望作者@[EAimTY](https://github.com/EAimTY)来review一下。

**Comment by EAimTY** [comment]
新的协议版本 5 以及新的测试版本已经实现了 UDP fragmentation，理论上解决了这些问题
