### ISSUE TITLE
疑问：关于congestion-controller拥塞控制的问题？

### ISSUE THREAD

**Issue by moranno** [EAimTY/tuic#62]
在一个丢包率大概在15-20%的服务器上，尝试过"cubic", "new_reno", "bbr"3种拥塞控制，目前测试下来，BBR的速度最好，
使用sppedtest.net测速单线程17mbps，多线程100mbps
而"cubic", "new_reno"，单线程不到1mbps，多线程也不到1mbps。

似乎客户端可以任意填写3种的一种，都可以和服务端正常通信，测速只受服务端congestion-controller配置影响。

请问为何差距如此大？这3种的应用场景有和讲究？

edit: 发现似乎cubic在网络质量好的情况下，单线程速度比bbr好，但多线程也还是不及bbr。

**Comment by zephyrchien** [comment]
用于翻墙的话全都开bbr就行了，至少服务端要开bbr, 其他算法一旦丢包就会急速退让。拥塞控制影响的是发包速率，也就是上传速度。你测试的应该是客户端的下载速度(服务端的上传速度)，在服务端都开了bbr的情况下结果自然是差不多的。

具体的建议自行搜索资料

**Comment by Fhokud** [comment]
> 在一个丢包率大概在15-20%的服务器上，尝试过"cubic", "new_reno", "bbr"3种拥塞控制，目前测试下来，BBR的速度最好， 使用sppedtest.net测速单线程17mbps，多线程100mbps 而"cubic", "new_reno"，单线程不到1mbps，多线程也不到1mbps。
> 
> 似乎客户端可以任意填写3种的一种，都可以和服务端正常通信，测速只受服务端congestion-controller配置影响。
> 
> 请问为何差距如此大？这3种的应用场景有和讲究？
> 
> edit: 发现似乎cubic在网络质量好的情况下，单线程速度比bbr好，但多线程也还是不及bbr。

请自行补习知识：拥塞控制算法

**Comment by Fhokud** [comment]
cubic：各方妥协的默认控制算法
new_reno：曾经的候选默认拥塞控制算法改进版
  他们都基于事件驱动（丢包），有较好的公平性


bbr：基于延迟计算发现丢包，并周期性试探最大带宽
  自闭算法，公平性存疑（被认为是抢占cubic的带宽）
