### ISSUE TITLE
关于TCP relaying和UDP relaying模式的疑问？

### ISSUE THREAD

**Issue by moranno** [EAimTY/tuic#65]
我看似乎tuic有2种工作模式TCP和UDP，但文档中似乎没有写明如何配置才能工作在不同的2种模式下。

请明示，感谢这么好的项目！

**Comment by cute** [comment]
udp_relay_mode 模式只有客户端支持。
都是基于 QUIC协议的转发，native 模式是使用 QUIC 的 datagram，quic 模式是使用 QUIC 的 unidirectional stream。
前者受限于MAX_DATAGRAM_FRAME_SIZE，不能转发大于 1163 - 8 -（address length） 的 udp 包。后者不受限制。

```
{
    "relay": {
        "server": "tuic.dev",
        "port": 8000,
        "token": "123456",
        "ip": "127.0.0.1",
        "certificates": ["./tuic.dev.crt"],
        "udp_relay_mode": "quic",
        "congestion_controller": "cubic",
        "heartbeat_interval": 10000,
        "alpn": ["h3"],
        "disable_sni": false,
        "reduce_rtt": false,
        "request_timeout": 8000,
        "max_udp_relay_packet_size": 5000
    },
    "local": {
        "port": 1080,
        "ip": "127.0.0.1"
    },
    "log_level": "info"
}
```

**Comment by moranno** [comment]
> udp_relay_mode 模式只有客户端支持。 都是基于 QUIC协议的转发，native 模式是使用 QUIC 的 datagram，quic 模式是使用 QUIC 的 unidirectional stream。 前者受限于MAX_DATAGRAM_FRAME_SIZE，不能转发大于 1163 - 8 -（address length） 的 udp 包。后者不受限制。
> 
> ```
> {
>     "relay": {
>         "server": "tuic.dev",
>         "port": 8000,
>         "token": "123456",
>         "ip": "127.0.0.1",
>         "certificates": ["./tuic.dev.crt"],
>         "udp_relay_mode": "quic",
>         "congestion_controller": "cubic",
>         "heartbeat_interval": 10000,
>         "alpn": ["h3"],
>         "disable_sni": false,
>         "reduce_rtt": false,
>         "request_timeout": 8000,
>         "max_udp_relay_packet_size": 5000
>     },
>     "local": {
>         "port": 1080,
>         "ip": "127.0.0.1"
>     },
>     "log_level": "info"
> }
> ```

感谢解惑，那请问这2种模式具体有什么区别呢？各有什么优劣？
看到你的另一个issue，好像说的quic模式下udp quic 连续发送 99 个后就无法继续传输了?是不是你说的“前者受限于MAX_DATAGRAM_FRAME_SIZE，不能转发大于 1163 - 8 -（address length） 的 udp 包。”请问会带来什么问题？

**Comment by cute** [comment]
> > udp_relay_mode 模式只有客户端支持。 都是基于 QUIC协议的转发，native 模式是使用 QUIC 的 datagram，quic 模式是使用 QUIC 的 unidirectional stream。 前者受限于MAX_DATAGRAM_FRAME_SIZE，不能转发大于 1163 - 8 -（address length） 的 udp 包。后者不受限制。
> > ```
> > {
> >     "relay": {
> >         "server": "tuic.dev",
> >         "port": 8000,
> >         "token": "123456",
> >         "ip": "127.0.0.1",
> >         "certificates": ["./tuic.dev.crt"],
> >         "udp_relay_mode": "quic",
> >         "congestion_controller": "cubic",
> >         "heartbeat_interval": 10000,
> >         "alpn": ["h3"],
> >         "disable_sni": false,
> >         "reduce_rtt": false,
> >         "request_timeout": 8000,
> >         "max_udp_relay_packet_size": 5000
> >     },
> >     "local": {
> >         "port": 1080,
> >         "ip": "127.0.0.1"
> >     },
> >     "log_level": "info"
> > }
> > ```
> 
> 感谢解惑，那请问这2种模式具体有什么区别呢？各有什么优劣？ 看到你的另一个issue，好像说的quic模式下udp quic 连续发送 99 个后就无法继续传输了?是不是你说的“前者受限于MAX_DATAGRAM_FRAME_SIZE，不能转发大于 1163 - 8 -（address length） 的 udp 包。”请问会带来什么问题？

带来的问题就是转发 udp 失败。
另一个问题是我使用库实现的问题。

**Comment by zephyrchien** [comment]
一般情况下，建议用native模式。使用udp的应用通常会允许丢包，比如短时间内发送几个小包，以最先到达的为准，剩下的可以忽略，没必要重传。 对于重要的数据包，应用通常也有自己的重传机制。

**Comment by cute** [comment]
> 一般情况下，建议用native模式。使用udp的应用通常会允许丢包，比如短时间内发送几个小包，以最先到达的为准，剩下的可以忽略，没必要重传。 对于重要的数据包，应用通常也有自己的重传机制。

如果 udp + overhead 包大于 MAX_DATAGRAM_FRAME_SIZE，比如 http3 的应用，native 模式则无法使用， 即使 http3 有重传机制也没用。

**Comment by zephyrchien** [comment]
> > 一般情况下，建议用native模式。使用udp的应用通常会允许丢包，比如短时间内发送几个小包，以最先到达的为准，剩下的可以忽略，没必要重传。 对于重要的数据包，应用通常也有自己的重传机制。
> 
> 如果 udp + overhead 包大于 MAX_DATAGRAM_FRAME_SIZE，比如 http3 的应用，native 模式则无法使用， 即使 http3 有重传机制也没用。

目前确实是这样，需要等待 #61 解决

**Comment by EAimTY** [comment]
TCP relaying 与 UDP relaying 并非是两种“模式”，只是将 client 端 TCP 与 UDP 转发到 server 端各自的方式而已，相互间没有替代关系。

UDP relaying 部分目前还有很多 BUG 与设计上的问题需要解决，之后会尽快更新修复。

**Comment by fannwong001** [comment]
> TCP relaying 与 UDP relaying 并非是两种“模式”，只是将 client 端 TCP 与 UDP 转发到 server 端各自的方式而已，相互间没有替代关系。
> 
> 
> 
> UDP relaying 部分目前还有很多 BUG 与设计上的问题需要解决，之后会尽快更新修复。

这种说法确实容易误解，开始我也以为是使用tcp承载或者udp承载了，因为gost里面有relay协议 他的比较早（顺便说一下他的那些文档说明和术语也很让人迷惑）。我觉得改成代理tcp或者代理udp比较好。
