### ISSUE TITLE
服务端过滤规则？

### ISSUE THREAD

**Issue by ma-chengyuan** [EAimTY/tuic#68]
虽然在客户端可以通过前置v2ray/clash转发来实现国内/国外请求的分流，为了保险起见（因为据称用VPS访问国内IP是不推荐行为会显著提升识别率），最好也应该在服务端设置block所有geoip是cn的请求。这就不能通过在下游串联其他服务来实现了，而如果通过iptables的方式全局禁止连接国内ip，不仅麻烦不灵活而且很难对客户端的ip网开一面。这么看来除了把这种功能做进TUIC以外还有什么比较方便的解决方法？

**Comment by Fhokud** [comment]
tuic是rust实现的，实现上述功能要自写大量代码，且后期会让软件变得臃肿，况且这些功能有大量其他软件有优秀的实现，为什么要重复开发，浪费精力呢？

**Comment by ma-chengyuan** [comment]
> 从我的实际经验来看，服务端访问CN并不会带来被封概览增加的问题。

我是参考 https://github.com/XTLS/Xray-core/discussions/593#discussioncomment-845165 里的建议。我个人也没有被封过，但是科学上网每个人的经历差异很大，anecdotal evidence 很多，觉得还是保险一点比较好。

> tuic是rust实现的，实现上述功能要自写大量代码，且后期会让软件变得臃肿，况且这些功能有大量其他软件有优秀的实现，为什么要重复开发，浪费精力呢？

赞同！根据UNIX哲学TUIC不应该包含这方面的特性，我个人也不赞成重复造轮子。但是在服务端TUIC目前直连外网，如果要控制访问的话很难和其他软件配合，好像除了iptables没有有效的方案，所以想在这个issue里面探讨一下有没有什么好方法。

**Comment by bash99** [comment]
> > 从我的实际经验来看，服务端访问CN并不会带来被封概览增加的问题。
> 
> 我是参考 [XTLS/Xray-core#593 (comment)](https://github.com/XTLS/Xray-core/discussions/593#discussioncomment-845165) 里的建议。我个人也没有被封过，但是科学上网每个人的经历差异很大，anecdotal evidence 很多，觉得还是保险一点比较好。
> 
> > tuic是rust实现的，实现上述功能要自写大量代码，且后期会让软件变得臃肿，况且这些功能有大量其他软件有优秀的实现，为什么要重复开发，浪费精力呢？
> 
> 赞同！根据UNIX哲学TUIC不应该包含这方面的特性，我个人也不赞成重复造轮子。但是在服务端TUIC目前直连外网，如果要控制访问的话很难和其他软件配合，好像除了iptables没有有效的方案，所以想在这个issue里面探讨一下有没有什么好方法。

如果服务器端tuic支持代理，可以套一层 v2ray/xray/verysimple 之类的工具实现

**Comment by EAimTY** [comment]
我认为 TUIC server 不应添加这项功能，正如你们所提到的，这会增加软件的复杂度并增大维护难度。

目前我觉得可行的方法是利用 cgroups 将 TUIC server 的流量重定向至 v2ray 的 TPROXY 进行分流。可以使用的实现有 [cproxy](https://github.com/NOBLES5E/cproxy) 与 [cgproxy](https://github.com/springzfx/cgproxy)。

我之后计划重构 server 与 client 实现，整理 API 后发布为 crate。这一步完成后，基于 TUIC 的二次开发会变得更加简单，如果需要类似的功能就可以比较容易地自行实现了。

**Comment by karelrooted** [comment]
使用cproxy，本身tuic-server到tuic-client的响应也会经过一层tproxy, 可以额外增加一条iptables规则跳过
sudo iptables -t mangle -I OUTPUT -p udp -d  {input_your_ip}/16 -j RETURN
