### ISSUE TITLE
是否能提供tuic协议完整的spec？

### ISSUE THREAD

**Issue by StashNetworks** [EAimTY/tuic#7]
如果可以的话，我们团队可以尝试移植到[Stash代理软件](https://apps.apple.com/app/stash/id1596063349)里面去。

**Comment by EAimTY** [comment]
可以，但是之后协议很有可能会再改动，目前协议还有很多能优化的地方，而且其中的 `bind` 命令还未实现，只是一个占位符。
我会尽快把协议内容整理出来，谢谢你们的帮助！

**Comment by EAimTY** [comment]
这里是协议完整 spec：https://github.com/EAimTY/tuic/tree/master/protocol
