### ISSUE TITLE
恭喜tuic被收录于awesome-vpn/wiki/Cores

### ISSUE THREAD

**Issue by hugetiny** [EAimTY/tuic#73]
https://github.com/awesome-vpn/awesome-vpn/wiki/Cores

这个wiki是基于vpn中协议的对比，我一直在思考是否要将HTTP/TCP/UDP等基础协议是否也加入对比，因为这些基础协议基本都支持。
全部写出来显得冗余。修改了一个新版本，欢迎再次修改

**Comment by Fhokud** [comment]
似乎列出了一些不安全实现

**Comment by hugetiny** [comment]
> 似乎列出了一些不安全实现

列表中的确有旧的ciphers会标注deprecated

WIKI是公开的，有想法请随意修改
