### ISSUE TITLE
服务端0.8.3/0.8.2接收UDP包后服务端崩溃

### ISSUE THREAD

**Issue by Fhokud** [EAimTY/tuic#75]
使用tuic-server-0.8.2-x86_64-linux-gnu
配置文件在此https://github.com/EAimTY/tuic/issues/55#issue-1294492283

**Comment by Fhokud** [comment]
服务端0.8.1/0.8.2在客户端0.8.2尝试通过socks发送一个udp数据包后无响应，需要重启服务端
udp模式：quic

**Comment by Fhokud** [comment]
客户端0.8.2 服务端0.8.1
此时udp可以正常工作，包括Full Cone NAT

**Comment by Fhokud** [comment]
@EAimTY

**Comment by EAimTY** [comment]
已在 662491fc586ea18cf5ad3aeb7e3baf0674647f0e 中修复，马上会发 0.8.3 版本

在 dual-stack socket 上用 epoll 的坑实在是太多了

**Comment by Fhokud** [comment]
@EAimTY 0.8.3一个样

**Comment by Fhokud** [comment]
服务端只要是0.8.1
客户端0.8.2/0.8.3能正常处理udp和Full Cone NAT支持

**Comment by Fhokud** [comment]
https://github.com/EAimTY/tuic/releases/tag/0.8.5
已修复
