### ISSUE TITLE
0.85 for windows 被误判病毒？

### ISSUE THREAD

**Issue by delphinuz** [EAimTY/tuic#76]
不知什么原因，但给作者参考

https://imgur.com/1YeT338

VirusTotal 的[结果](https://www.virustotal.com/gui/file/ee8aeb4e58c75b5b725d7f5036bead42278137036a49a96648344644b135f428/detection)

**Comment by EAimTY** [comment]
请问之前的几个版本（0.8.4/0.8.3/0.8.2/0.8.1）有类似问题吗？Releases 都是直接用 GitHub Actions 编译出的 binary，除非上游工具链被感染，否则不可能被偷偷加料。

**Comment by chika0801** [comment]
0.84 0.81 win11自带杀毒程序 ，没报

**Comment by YongChingShieh** [comment]
我这边自带杀毒软件并没有警告 但chrome直接删除....
![Annotation 2022-08-07 094933](https://user-images.githubusercontent.com/24885976/183271636-00c52f2a-f3aa-40f2-936d-bf926bbc142c.jpg)
