### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by Mr-xn** [EAimTY/tuic#8]
error log:
```
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found
```

建议自己在服务端编译，客服端也自己编译，不然很多莫名其妙的错误
linux ubuntu 大致编译 
```bash
apt -y install curl git
git clone https://github.com/EAimTY/tuic
curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh
source $HOME/.cargo/env 
cd tuic/
cargo build
```
结果文件就在  `tuic/target/debug/`

> 我虽然编译成功了，但还是连不上....
> 同志还需努力多测试啊

**Comment by EAimTY** [comment]
这个是你的 glibc 版本太低的问题。
我怀疑前面几个 issue 的问题也是出在动态链接库上，下次发布的时候我会改成静态链接。
另外，自己编译至少也要带上 --release 参数，debug 的性能低很多
