### ISSUE TITLE
TUIC 速度会被限制在一个地方无法更快

### ISSUE THREAD

**Issue by Skyxim** [EAimTY/tuic#82]
<img width="728" alt="image" src="https://user-images.githubusercontent.com/70276018/186546783-9bacf684-f4f1-4f43-9357-1399301a9efc.png">

我用电脑跑 TUIC 速度会在瞬间到达 80，然后呈现上下摆动略微上涨点速度，但是几乎不动 

同机器 SS 可以单线程 300+，同是基于 QUIC 的 Hysteria 也可以跑到 300 （这个只是说明没有 UDP QoS），这些速度都是在 M1 上测得，应该不是性能 CPU 瓶颈

是否 TUIC 有特定参数进行限速

client config
```
{
    "relay": {
        "server": "domain",
        "ip": "ip",
        "port": 8043,
        "token": "password",
        "udp_relay_mode": "native",
        "certificates": [
            "/Users/frost/data/codes/cert/ca.pem"
        ],
        "congestion_controller": "bbr",
        "heartbeat_interval": 10000,
        "alpn": [
            "h3"
        ],
        "disable_sni": false,
        "reduce_rtt": true,
        "request_timeout": 8000,
        "max_udp_relay_packet_size": 1500
    },
    "local": {
        "port": 60000,
        "ip": "127.0.0.1"
    },
    "log_level": "debug"
}
```

server config
```
{
    "port": 8043,
    "token": ["password"],
    "certificate": "/etc/ssl/certs/skyxim.fullchain.pem",
    "private_key": "/etc/ssl/private/skyxim.server.key",
    "ip": "::",
    "congestion_controller": "bbr",
    "max_idle_time": 15000,
    "authentication_timeout": 1000,
    "alpn": ["h3"],
    "max_udp_relay_packet_size": 1500,
    "log_level": "debug"
}
```

**Comment by chika0801** [comment]
建议sp测多线程。或者你本地电脑上用IDM挂代理，走你VPS。IDM开16线程，下大文件，看极限速度。

**Comment by Skyxim** [comment]
> 建议sp测多线程。或者你本地电脑上用IDM挂代理，走你VPS。IDM开16线程，下大文件，看极限速度。

多线程以 单线程 80 肯定轻轻松松跑满带宽，但是没啥意义，并不是为了测速而测速。用单线程就是想看效果

**Comment by chika0801** [comment]
> 多线程以 单线程 80 肯定轻轻松松跑满带宽，但是没啥意义，并不是为了测速而测速。用单线程就是想看实际加速效果

那说明你用TUIC，跑单线程，就这样速度了。



>  是否 TUIC 有特定参数进行限速

没有。

**Comment by EAimTY** [comment]
不考虑环境，速度受限的原因可能有两个：

- 受底层库 quinn 的性能限制
- 这个 TUIC 实现本身质量不佳，特别是 client 部分，有很多不必要的逻辑

我最近正在重构这个项目的结构，把不硬性依赖运行时的部分独立出一个库。这样可以很大程度上解决实现不佳的问题。后续我有计划将 TUIC 在 QUIC 上的 wrapper 改为 Trait 形式，让后端依赖的 QUIC 实现可以更换。但这个计划目前有两个 blocking 项：

1. Rust 生态中其它 QUIC 实现没有可更改的拥塞控制
2. Rust 语言还不支持原生的 async trait

**Comment by chika0801** [comment]
感谢作者回复，期待下个版本！

**Comment by Skyxim** [comment]
> 不考虑环境，速度受限的原因可能有两个：
> 
> * 受底层库 quinn 的性能限制
> * 这个 TUIC 实现本身质量不佳，特别是 client 部分，有很多不必要的逻辑
> 
> 我最近正在重构这个项目的结构，把不硬性依赖运行时的部分独立出一个库。这样可以很大程度上解决实现不佳的问题。后续我有计划将 TUIC 在 QUIC 上的 wrapper 改为 Trait 形式，让后端依赖的 QUIC 实现可以更换。但这个计划目前有两个 blocking 项：
> 
> 1. Rust 生态中其它 QUIC 实现没有可更改的拥塞控制
> 2. Rust 语言还不支持原生的 async trait

1. 可以尝试下 Cloudflare 的 quiche 我好像看到支持 cubic、bbr、reno
等待后续重构吧

**Comment by zephyrchien** [comment]
> > 不考虑环境，速度受限的原因可能有两个：
> > 
> > * 受底层库 quinn 的性能限制
> > * 这个 TUIC 实现本身质量不佳，特别是 client 部分，有很多不必要的逻辑
> > 
> > 我最近正在重构这个项目的结构，把不硬性依赖运行时的部分独立出一个库。这样可以很大程度上解决实现不佳的问题。后续我有计划将 TUIC 在 QUIC 上的 wrapper 改为 Trait 形式，让后端依赖的 QUIC 实现可以更换。但这个计划目前有两个 blocking 项：
> > 
> > 1. Rust 生态中其它 QUIC 实现没有可更改的拥塞控制
> > 2. Rust 语言还不支持原生的 async trait
> 
> 1. 可以尝试下 Cloudflare 的 quiche 我好像看到支持 cubic、bbr、reno
>    等待后续重构吧

cloudflare的quiche-rs [还没有实现bbr](https://docs.rs/quiche/latest/quiche/enum.CongestionControlAlgorithm.html)， google的quiche倒是有bbr，但是难用，跟rust结合起来就更麻烦了。

**Comment by Skyxim** [comment]
> > > 不考虑环境，速度受限的原因可能有两个：
> > > 
> > > * 受底层库 quinn 的性能限制
> > > * 这个 TUIC 实现本身质量不佳，特别是 client 部分，有很多不必要的逻辑
> > > 
> > > 我最近正在重构这个项目的结构，把不硬性依赖运行时的部分独立出一个库。这样可以很大程度上解决实现不佳的问题。后续我有计划将 TUIC 在 QUIC 上的 wrapper 改为 Trait 形式，让后端依赖的 QUIC 实现可以更换。但这个计划目前有两个 blocking 项：
> > > 
> > > 1. Rust 生态中其它 QUIC 实现没有可更改的拥塞控制
> > > 2. Rust 语言还不支持原生的 async trait
> > 
> > 
> > 
> > 1. 可以尝试下 Cloudflare 的 quiche 我好像看到支持 cubic、bbr、reno
> >    等待后续重构吧
> 
> cloudflare的quiche-rs [还没有实现bbr](https://docs.rs/quiche/latest/quiche/enum.CongestionControlAlgorithm.html)， google的quiche倒是有bbr，但是难用，跟rust结合起来就更麻烦了。

https://github.com/cloudflare/quiche/tree/master/quiche/src/recovery/bbr
哦，刚刚才提交的，可能文档没有更新

**Comment by zephyrchien** [comment]
> 不考虑环境，速度受限的原因可能有两个：
> 
> * 受底层库 quinn 的性能限制
> * 这个 TUIC 实现本身质量不佳，特别是 client 部分，有很多不必要的逻辑
> 
> 我最近正在重构这个项目的结构，把不硬性依赖运行时的部分独立出一个库。这样可以很大程度上解决实现不佳的问题。后续我有计划将 TUIC 在 QUIC 上的 wrapper 改为 Trait 形式，让后端依赖的 QUIC 实现可以更换。但这个计划目前有两个 blocking 项：
> 
> 1. Rust 生态中其它 QUIC 实现没有可更改的拥塞控制
> 2. Rust 语言还不支持原生的 async trait

我个人觉得现阶段用~~钦定~~quinn就可以了。BTW, Rust开启GAT以后是可以写出async trait的，但是需要手写Future。

**Comment by zephyrchien** [comment]
> 

那可太棒了。另外这个库需要封装一下才能像quinn那样用async/await

**Comment by chika0801** [comment]
## 选择建议

- 回程线路好，CPU性能好 TUIC = hysteria = Trojan-TCP-TLS
- 回程线路好，CPU性能差 TUIC > Trojan-TCP-TLS > hysteria
- 回程线路差，CPU性能好/差 hysteria > TUIC > Trojan-TCP-TLS

## 测速结果

联通，Windows 11，Chrome -> Proxy SwitchyOmega(HTTP) -> v2rayN -> VPS

使用[speedtest.net](https://www.speedtest.net)网页版，多线程，以结束时显示的值为结果，测3次，取平均值。（香港服务器ID 22126，圣何塞服务器ID 49365，大阪服务器ID 21569，东京服务器ID 21569，堪萨斯城服务器ID 45852）

<details><summary>点击查看</summary> 

```
大阪（BBTEC回程 1核 512M 10G SSD 2.5Gbps带宽）
Trojan-TCP-TLS 505Mbps
hysteria       255Mbps（客户端配置最大下载速度300Mbps）
TUIC           570Mbps
```

```
东京（BBTEC回程 1核 1G 15G SSD 500Mbps带宽）
Trojan-TCP-TLS 479Mbps
hysteria       485Mbps（客户端配置最大下载速度500Mbps）
TUIC           366Mbps
```

```
东京（IIJ回程 2核 2.5G 50G SSD 1Gbps带宽）
Trojan-TCP-TLS 707Mbps
hysteria       671Mbps（客户端配置最大下载速度800Mbps）
TUIC           425Mbps
```

```
东京（NTT回程 1核 2G 15G SSD 10Gbps带宽）
Trojan-TCP-TLS 311Mbps
hysteria       459Mbps（客户端配置最大下载速度500Mbps）
TUIC           390Mbps
```

```
东京（Azure回程 1核 1G 64G SSD 10Gbps带宽）
Trojan-TCP-TLS 644Mbps
hysteria       667Mbps（客户端配置最大下载速度700Mbps）
TUIC           564Mbps
```

```
香港（CMI回程 1核 1G 15G SSD 500Mbps带宽）
Trojan-TCP-TLS 461Mbps
hysteria       486Mbps（客户端配置最大下载速度500Mbps）
TUIC           354Mbps
```

```
香港（BBTEC回程 2核 8G 40G SSD 10Gbps带宽）
Trojan-TCP-TLS 349Mbps
hysteria       111Mbps（客户端配置最大下载速度300Mbps）
TUIC           244Mbps
```

```
圣何塞（9929回程 2核 1G 20G SSD 1Gbps带宽）
Trojan-TCP-TLS 482Mbps
hysteria       595Mbps（客户端配置最大下载速度650Mbps）
TUIC           262Mbps
```

```
圣何塞（GTT回程 1核 2G 20G SSD 10Gbps带宽）
Trojan-TCP-TLS 113Mbps
hysteria       439Mbps（客户端配置最大下载速度500Mbps）
TUIC           210Mbps
```

```
堪萨斯城（Telia回程 1核 2G 20G SSD 10Gbps带宽）
Trojan-TCP-TLS 116Mbps
hysteria       224Mbps（客户端配置最大下载速度300Mbps）
TUIC           152Mbps
```

</details>


使用[youtube.com](https://www.youtube.com/watch?v=I3o4WW4tD9M)播放4K视频，观看120秒，以稳定时的值为结果。

<details><summary>点击查看</summary> 

```
大阪（BBTEC）
Trojan-TCP-TLS  90000Kbps
hysteria       140000Kbps
TUIC            80000Kbps
```

```
东京（BBTEC）
Trojan-TCP-TLS 210000Kbps
hysteria       210000Kbps
TUIC           100000Kbps
```

```
东京（IIJ）
Trojan-TCP-TLS  90000Kbps
hysteria       160000Kbps
TUIC            50000Kbps
```

```
东京（NTT）
Trojan-TCP-TLS  40000Kbps
hysteria       180000Kbps
TUIC            40000Kbps
```

```
东京（Azure）
Trojan-TCP-TLS 220000Kbps
hysteria       200000Kbps
TUIC           100000Kbps
```

```
香港（CMI）
Trojan-TCP-TLS 150000Kbps
hysteria       180000Kbps
TUIC            70000Kbps
```

```
香港（BBTEC）
Trojan-TCP-TLS 120000Kbps
hysteria       100000Kbps
TUIC            60000Kbps
```

```
圣何塞（9929）
Trojan-TCP-TLS 110000Kbps
hysteria       180000Kbps
TUIC            50000Kbps
```

```
圣何塞（GTT）
Trojan-TCP-TLS  10000Kbps
hysteria        90000Kbps
TUIC            40000Kbps
```

```
堪萨斯城（Telia）
Trojan-TCP-TLS  20000Kbps
hysteria        60000Kbps
TUIC            30000Kbps
```

</details>
