### ISSUE TITLE
服务端配置文件路径在哪

### ISSUE THREAD

**Issue by mhnhh123** [EAimTY/tuic#83]
报错提示
配置成功
[] [Custom] bwg
启动服务(2022/9/1 20:54:40)...
启动服务(2022/9/1 20:54:41)...
Xray 1.5.10 (Xray, Penetrates Everything.) Custom (go1.18.5 windows/amd64)
A unified platform for anti-censorship.
2022/09/01 20:54:41 [Info] infra/conf/serial: Reading config: stdin:
2022/09/01 20:54:41 [Warning] core: Xray 1.5.10 started
2022/09/01 20:54:42 127.0.0.1:59275 accepted http://91.108.56.113:80/api [http -> proxy]
2022/09/01 20:54:42 127.0.0.1:59274 accepted //91.108.56.113:443 [http -> proxy]
2022/09/01 20:54:42 127.0.0.1:59266 accepted http://91.108.56.113:80/api [http -> proxy]
2022/09/01 20:54:42 127.0.0.1:59267 accepted http://91.108.56.113:80/api [http -> proxy]
2022/09/01 20:54:42 127.0.0.1:59268 accepted //mtalk.google.com:5228 [http -> proxy]
2022/09/01 20:54:43 127.0.0.1:59281 accepted //91.108.56.113:443 [http -> proxy]
2022/09/01 20:54:43 127.0.0.1:59282 accepted http://91.108.56.113:80/api [http -> proxy]
2022/09/01 20:54:47 127.0.0.1:59287 accepted //91.108.56.113:443 [http -> proxy]
2022/09/01 20:54:47 127.0.0.1:59288 accepted http://91.108.56.113:80/api [http -> proxy]
2022/09/01 20:54:49 127.0.0.1:59292 accepted //alive.github.com:443 [http -> proxy]
2022/09/01 20:54:50 [Warning] [209191103] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > proxy/socks: server rejects request: 3
2022/09/01 20:54:50 [Warning] [1637925803] app/proxyman/outbound: failed to process outbound traffic > proxy/socks: failed to establish connection to server > proxy/socks: server rejects request: 3
2022/09/01 20:54:50 [Warning] [1637925803] proxy/http: failed to read response from 91.108.56.113:80 > io: read/write on closed pipe
服务端配置文件
{
    "port": 44448,
    "token": ["mhnhh"],
    "certificate": "/path/to/cert",
    "private_key": "/path/to/key",

    "ip": "127.0.0.1",
    "congestion_controller": "bbr",
  
    "alpn": ["h3"],
    "max_udp_relay_packet_size": 1146,
    "log_level": "info"
}

   客户端配置文件
{
    "relay": {
        "server": "我的域名",
        "alpn": [
            "h3"
        ],
        "ip": "127.0.0.1",
        "token": "mhnhh",
        "port": 44448,
        "udp_relay_mode": "native",
        "reduce_rtt": true,
        "disable_sni": false,
        "max_udp_relay_packet_size": 1146,
        "congestion_controller": "bbr"
    },
    "log_level": "info",
    "local": {
        "ip": "127.0.0.1",
        "port": 38922
    }
}

**Comment by chika0801** [comment]
客户端配置文件
{
"relay": {
"server": "我的域名",
"alpn": [
"h3"
],
"ip": "127.0.0.1",      这里填VPS的IP或删除这行
"token": "mhnhh",
"port": 44448,
"udp_relay_mode": "native",
"reduce_rtt": true,
"disable_sni": false,
"max_udp_relay_packet_size": 1146,
"congestion_controller": "bbr"
},
"log_level": "info",          在N里用，这里改为OFF，BUG见
"local": {
"ip": "127.0.0.1",
"port": 38922
}
}
