### ISSUE TITLE
Windows7 启动报错Failed to load the certificate: BadDer

### ISSUE THREAD

**Issue by imshuai** [EAimTY/tuic#84]
### 系统版本及客户端版本  
* Windows7 64位  以及  安卓7
* [tuic-client-0.8.5-x86_64-windows-gnu.exe](https://github.com/EAimTY/tuic/releases/download/0.8.5/tuic-client-0.8.5-x86_64-windows-gnu.exe)
* [tuic-client-0.8.5-x86_64-windows-msvc.exe](https://github.com/EAimTY/tuic/releases/download/0.8.5/tuic-client-0.8.5-x86_64-windows-msvc.exe)
* SagerNet 安装Tuic插件

### Client配置文件  

```
{
    "relay": {
        "server": "server_name",
        "port": 8443,
        "token": "token",
        "ip": "server ip",
        "certificates": ["E:\\Program files\\v2rayN-Core\\cert.crt"],
        "udp_relay_mode": "quic",
        "congestion_controller": "bbr",
        "heartbeat_interval": 10000,
        "alpn": ["h3"],
        "disable_sni": false,
        "reduce_rtt": false,
        "request_timeout": 8000,
        "max_udp_relay_packet_size": 1500
    },
    "local": {
        "port": 23333,
        "ip": "127.0.0.1"
    },
    "log_level": "off"
}
```  

### Client启动命令  
```
tuic-client.exe -c tuic-client.json
```  

### 错误信息  
``` 
Failed to load the certificate: BadDer
```  

同样的配置及启动命令在linux下完全正常，在Windows7和安卓上就报错。证书为let's encrypted下发的web服务器证书。

**Comment by EAimTY** [comment]
猜测可能是证书编码问题，可以尝试手动将证书转换一下格式

**Comment by EAimTY** [comment]
#90
