### ISSUE TITLE
How to get this working

### ISSUE THREAD

**Issue by bigli0n** [EAimTY/tuic#85]
I went through the usual process of generating a self-signed CA , keys, and certificates for clients and server in multiple formats. I have tried .pem .crt and .cer and all of them fail with the error message "invalid peer certificate: UnsupportedCertVersion"

Edit: Translated another a previously posted issue, and the solution was "the end needs to provide the complete chain". Ok sure, but that's a little vague. Which end, the client the server or both? How to point TUIC to the full chain in the config file, because I only see the option for "certificate"

**Comment by EAimTY** [comment]
You need to provide the full certificate chain (eg. root cert + intermediate cert + end-entity cert) on the client side. A PEM/DER encoded cert file can include multiple cert, so you can put them into a single file. Besides, client option `--certificate` can be called multiple times, and the field `certificates` in the config file is an array - for supplying more than one cert file.

[rcgen](https://github.com/est31/rcgen) is a better self-signed CA generator for TUIC.
