### ISSUE TITLE
Bug: `quinn::connection::Connection::open_bi` will hang when reach `max_concurrent_bi_streams` limit

### ISSUE THREAD

**Issue by finpluto** [EAimTY/tuic#86]
Bug: 当同时开启的stream数到达quinn的`max_concurrent_bi_streams`（默认为100）上限后，调用`quinn::connection::Connection::open_bi()`将会挂起task，导致连接超时。

可以考虑的解决方案：
1. `tuic_client::relay::connection::Connection::get_bi_stream()`处通过`Register`的流计数实现自动扩容流上限
2. 加入可配置项允许用户设置`max_concurrent_bi_streams`值
3. 创建`quic::connection::Connection`时调用`set_max_concurrent_bi_streams`设置为更大值

---

Bug: `quinn::connection::Connection::open_bi` will hang when reach `max_concurrent_bi_streams` limit, cause relay task timeout.

possible solutions:
1. make `tuic_client::relay::connection::Connection::get_bi_stream()` call expand `max_concurrent_bi_streams` automatically;
2. add a configuration option to allow customizing the value of `max_concurrent_bi_stream`;
3. call `set_max_concurrent_bi_streams` with a number larger than 100 when creating `quic::connection::Connection`

---

refs:
- https://github.com/quinn-rs/quinn/issues/1231#issuecomment-1008331336

**Comment by finpluto** [comment]
![image_2022-09-14_22-23-13](https://user-images.githubusercontent.com/35735190/190351875-e9af95a3-bb20-4713-8a78-329dbee18c3b.png)

**Comment by finpluto** [comment]
临时补丁/work around

```diff
diff --git a/client/src/relay/connection.rs b/client/src/relay/connection.rs
index 1face7d..d4accc7 100644
--- a/client/src/relay/connection.rs
+++ b/client/src/relay/connection.rs
@@ -163,6 +163,9 @@ impl Connection {
             conn.await?
         };
 
+        connection.set_max_concurrent_bi_streams(65536u32.into());
+        connection.set_max_concurrent_uni_streams(65536u32.into());
+
         let conn = Self::new(connection, config).await;
         let uni_streams = IncomingUniStreams::new(uni_streams, conn.stream_reg.get_registry());
 

```

**Comment by EAimTY** [comment]
最近正在重构，打算用思路 1 解决这个问题。

quinn 的文档中提到的 [`max_concurrent_uni_streams`](https://docs.rs/quinn/latest/quinn/struct.Connection.html#method.set_max_concurrent_uni_streams)：

> Modify the number of remotely initiated unidirectional streams that may be concurrently open

因此 `max_concurrent_uni_streams` 的数值应只会影响 streams initiated by peer。目前 TUIC 的 register 只针对 task 进行计数，没有区分 stream 流向，所以需要重构这一部分

**Comment by EAimTY** [comment]
新版本已经实现了 `max_concurrent_bi_streams` 的自动扩容
