### ISSUE TITLE
Is ipv6 not supported?

### ISSUE THREAD

**Issue by freett** [EAimTY/tuic#9]
COMMAND   PID USER   FD   TYPE    DEVICE SIZE/OFF NODE NAME
tuic-serv        421   root      6u     IPv4    625337846      0t0  UDP *:9099

**Comment by EAimTY** [comment]
should be fixed in 2145073b8a3a56fdbb04ce02eda8e68b4cda8079

**Comment by freett** [comment]
Thanks!

EAimTY ***@***.***> 于 2022年3月23日周三 16:38写道：
