### ISSUE TITLE
无法加载证书 MissingOrMalformedExtensions

### ISSUE THREAD

**Issue by YongChingShieh** [EAimTY/tuic#90]
同样的配置 在Windows 10上提示
Failed to load the certificate: MissingOrMalformedExtensions
但在Windows11上没有问题
config:

> {
    "relay": {
        "server": "xxxxx",
        "port": 4433,
        "token": "token",
        "udp_relay_mode": "quic",
        "congestion_controller": "bbr",
        "heartbeat_interval": 10000,
        "alpn": ["h3"],
        "disable_sni": false,
        "reduce_rtt": true,
        "request_timeout": 8000,
        "max_udp_relay_packet_size": 1500
    },
    "local": {
        "port": 10082,
        "ip": "127.0.0.1"
    },
    "log_level": "info"
}

**Comment by nagaame** [comment]
你可能忘了加上`"certificates": ["/PATH/TO/CERT"],`字段

**Comment by YongChingShieh** [comment]
> 你可能忘了加上`"certificates": ["/PATH/TO/CERT"],`字段

问题这个字段是非必填....然后就是同样的配置 windows11可以 而windows10不可以....

**Comment by microjo** [comment]
同样的错误，我是windows11。

**Comment by cubolia** [comment]
同样有此错误，windows10系统

**Comment by mega-optimus** [comment]
this may have to do with the rustls-native-certs library or the schannel library
https://github.com/rustls/rustls-native-certs/pull/52

**Comment by EAimTY** [comment]
The newest version of tuic-client provide an option `disable_native_certs`. This may help to locate the bug
