### ISSUE TITLE
能否在服务端增加一个socks5_outbound 转发功能

### ISSUE THREAD

**Issue by yanbook** [EAimTY/tuic#91]
tuic客户端、服务端均没有控制路由转发的功能，客户端可以在tuic之前自己加一个其它软件比如v2ray来做分流等目的。能否在服务端也加一个比如socks5_outbound的出口转发功能，这样就能在tuic服务端之后增加一个v2ray之类来做到服务端分流功能了

**Comment by EAimTY** [comment]
见 #68

**Comment by chika0801** [comment]
> 见 #68

之前看了https://github.com/EAimTY/tuic/issues/68#issuecomment-1196837123 搜索了一下[cproxy](https://github.com/NOBLES5E/cproxy) 与 [cgproxy](https://github.com/springzfx/cgproxy) ，不会就放弃了

**Comment by ggggle** [comment]
cproxy之类的透明代理并不可行，因为会把server发给client的流量也进行代理，导致异常
