### ISSUE TITLE
Ipv6 support? 

### ISSUE THREAD

**Issue by littlesum** [EAimTY/tuic#93]
Ipv6 suport

ip: [“0.0.0.0”,”::”]
not work

**Comment by Fhokud** [comment]
If you need to listen on both IPv4 and IPv6, you can set the bind IP to the unspecified IPv6 address ::.

Try to configure with the next line
ip: ["::"]

**Comment by littlesum** [comment]
> Try binding to "::" (the ANY ADDRESSES for IPv6), and it will listen for IPv4 connects as well.

Config like this, only listen v6 port

**Comment by littlesum** [comment]
if config ip: “::” only listen v6 address

**Comment by littlesum** [comment]
> If you need to listen on both IPv4 and IPv6, you can set the bind IP to the unspecified IPv6 address ::.
> 
> Try to configure with the next line ip: ["::"]

ip can only appear once. ip: x.x.x.x ip: x.x.x.x will show err

**Comment by littlesum** [comment]
> > > Try binding to "::" (the ANY ADDRESSES for IPv6), and it will listen for IPv4 connects as well.
> 
> > 
> 
> > Config like this, only listen v6 port
> 
> 
> 
> Binding to "::" works fine in most use cases.
> 
> Which linux distribution are you using?
> 
> I presume it is an OS issue.

Thanks it work now !
