### ISSUE TITLE
可否作为隧道使用？

### ISSUE THREAD

**Issue by neu-white** [EAimTY/tuic#96]
不好意思，这个不是issue，但是没有discussion，发这里希望路过的大佬帮忙解答下，谢谢🙏🏻️

想问能否做到，或使用什么工具能做到：remote--trojan--tuic------tuic--relay------trojan--local
我看了 #49 提到的工具，但可能是没太完全理解，似乎不适用于我这种情况。

**Comment by Fhokud** [comment]
A(Trojan--socks--Tuic client)----> B(Tuic server )-----> C(Trojan server)


A部分可以通过*ray-core直接实现，让Trojan出站走socks进Tuic client

**Comment by EAimTY** [comment]
这样做有什么意义？不仅增加了复杂度，还会造成出现多层拥塞控制

**Comment by houpi** [comment]
哈哈，我也在想这个，原因是我这quic的qos比较松，速度比Trojan 快，这样搞Trojan 用户不需要变更配置

**Comment by houpi** [comment]
问题解决了，用的gost建的quic隧道，只不过cpu占用比较高
