### ISSUE TITLE
client有计划支持http proxy port吗？

### ISSUE THREAD

**Issue by qingyinge-em** [EAimTY/tuic#99]
仅支持http proxy的应用更多

**Comment by Fhokud** [comment]
与#31 #35 重复

**Comment by nagaame** [comment]
个人的一点小建议，可以直接在clash添加一个tuic socks5 server，然后就可以转发出http端口了，而且clash还有分流，优点是有分流和满足你的需求，缺点就是需要依赖clash

**Comment by zephyrchien** [comment]
我这有个自用的补丁， 可以实现Socks5/HTTP同端口入站

<details>
<summary>Patch</summary>

```diff
From 730b40f1fb736ac7f97cf43783ae843236575ef1 Mon Sep 17 00:00:00 2001
From: zephyr <i@zephyr.moe>
Date: Fri, 26 Aug 2022 00:56:19 +0900
Subject: [PATCH] add http inbound

---
 client/Cargo.toml        |   3 +
 client/src/http/mod.rs   | 180 +++++++++++++++++++++++++++++++++++++++
 client/src/main.rs       |   1 +
 client/src/socks5/mod.rs |  52 ++++++++---
 4 files changed, 225 insertions(+), 11 deletions(-)
 create mode 100644 client/src/http/mod.rs

diff --git a/client/Cargo.toml b/client/Cargo.toml
index 1e11d5a..574a7f5 100644
--- a/client/Cargo.toml
+++ b/client/Cargo.toml
@@ -35,3 +35,6 @@ socks5-server = "0.8.*"
 thiserror = "1.0.*"
 tokio = { version = "1.20.*", features = ["io-util", "macros", "net", "parking_lot", "rt-multi-thread", "sync", "time"] }
 webpki = { version = "0.22.*", default-features = false }
+
+http = "0.2"
+httparse = "1"
diff --git a/client/src/http/mod.rs b/client/src/http/mod.rs
new file mode 100644
index 0000000..c230b04
--- /dev/null
+++ b/client/src/http/mod.rs
@@ -0,0 +1,180 @@
+use std::io::{Error, ErrorKind, Result};
+
+use tokio::io::{AsyncReadExt, AsyncWriteExt};
+use tokio::net::TcpStream;
+use tokio::sync::mpsc::Sender;
+
+use http::header::{HeaderMap, HeaderName, HeaderValue};
+use http::request::{Parts, Request};
+use http::{Method, Version};
+
+use crate::relay::Address as ProxyAddress;
+use crate::relay::Request as ProxyRequest;
+
+pub async fn handle(stream: &mut TcpStream, req_tx: Sender<ProxyRequest>) -> Result<()> {
+    let mut buf = vec![0u8; 0x2000];
+    let n = stream.read(&mut buf).await?;
+
+    let (mut request, head_n) = parse_request(&buf[..n])?;
+
+    // connect https
+    if request.method() == Method::CONNECT && request.version() == Version::HTTP_11 {
+        let addr = ProxyAddress::DomainAddress(
+            request.uri().host().unwrap().into(),
+            request.uri().port_u16().unwrap_or(443),
+        );
+        return handle_connect(stream, req_tx, addr).await;
+    }
+
+    // forward http
+    rm_proxy_hdrs(request.headers_mut());
+    // buf: 0 .. head_m .. head_n .. m .. n
+    let (parts, _) = request.into_parts();
+    let head_m = write_request_hdr(&parts, &mut buf[..head_n]);
+    let m = n - (head_n - head_m);
+    unsafe {
+        let count = m - head_m;
+        let src = buf.as_ptr().add(head_n);
+        let dst = buf.as_mut_ptr().add(head_m);
+        std::ptr::copy(src, dst, count);
+    };
+    let addr = ProxyAddress::DomainAddress(
+        parts.uri.host().unwrap().into(),
+        parts.uri.port_u16().unwrap_or(80),
+    );
+
+    log::info!(
+        "[http] [{}] [{}] [{}]",
+        stream.peer_addr().unwrap(),
+        parts.method.as_str(),
+        &addr
+    );
+
+    let (req, rx) = ProxyRequest::new_connect(addr);
+    let _ = req_tx.send(req).await;
+
+    let mut quic_stream = rx.await.map_err(map_io_err)?;
+    quic_stream.write_all(&buf[..m]).await?;
+    tokio::io::copy_bidirectional(stream, &mut quic_stream).await?;
+
+    Ok(())
+}
+
+async fn handle_connect(
+    stream: &mut TcpStream,
+    req_tx: Sender<ProxyRequest>,
+    addr: ProxyAddress,
+) -> Result<()> {
+    log::info!(
+        "[http] [{}] [CONNECT] [{}]",
+        stream.peer_addr().unwrap(),
+        &addr
+    );
+
+    let (req, rx) = ProxyRequest::new_connect(addr);
+    let _ = req_tx.send(req).await;
+
+    let mut quic_stream = rx.await.map_err(map_io_err)?;
+    stream
+        .write_all(b"HTTP/1.1 200 Connection Established\r\n\r\n")
+        .await?;
+
+    tokio::io::copy_bidirectional(stream, &mut quic_stream)
+        .await
+        .map(|_| ())
+}
+
+fn rm_proxy_hdrs(headers: &mut HeaderMap) {
+    headers.remove("proxy-connection");
+    headers.remove("proxy-authenticate");
+    headers.remove("proxy-authorization");
+    headers.remove("te");
+    headers.remove("trailers");
+    headers.remove("transfer-encoding");
+    headers.remove("upgrade");
+
+    if let Some(keys) = headers.remove("connection") {
+        let keys = std::str::from_utf8(keys.as_bytes()).unwrap();
+        for key in keys.split(',').map(str::trim) {
+            headers.remove(key);
+        }
+    }
+}
+
+fn write_request_hdr(parts: &Parts, mut buf: &mut [u8]) -> usize {
+    use std::io::Write;
+    let mut n = 0;
+
+    macro_rules! w {
+        ( $b: expr $(, $bx: expr)* ) => {
+            n += buf.write($b).unwrap();
+            $(
+                n += buf.write($bx).unwrap();
+            )*
+        };
+    }
+
+    // first line
+    let method = parts.method.as_str().as_bytes();
+    let path_query = parts.uri.path_and_query().unwrap().as_str().as_bytes();
+    let version = match parts.version {
+        Version::HTTP_10 => b"HTTP/1.0",
+        Version::HTTP_11 => b"HTTP/1.1",
+        _ => unreachable!(),
+    };
+    w![method, b" ", path_query, b" ", version, b"\r\n"];
+
+    for (key, value) in parts.headers.iter() {
+        w!(key.as_str().as_bytes(), b": ", value.as_bytes(), b"\r\n");
+    }
+
+    w!(b"\r\n");
+
+    n
+}
+
+fn parse_request(buf: &[u8]) -> Result<(Request<()>, usize)> {
+    use httparse::{Request, Status, EMPTY_HEADER};
+
+    let mut headers = [EMPTY_HEADER; 128];
+    let mut request = Request::new(&mut headers);
+
+    let head_n = match request.parse(buf).map_err(map_io_err)? {
+        Status::Complete(n) => n,
+        Status::Partial => return Err(new_io_err("unknown protocol")),
+    };
+
+    let mut headers = HeaderMap::from_iter(request.headers.iter().map(|hdr| {
+        (
+            HeaderName::from_bytes(hdr.name.as_bytes()).unwrap(),
+            HeaderValue::from_bytes(hdr.value).unwrap(),
+        )
+    }));
+
+    let version = match request.version.unwrap() {
+        0u8 => Version::HTTP_10,
+        1u8 => Version::HTTP_11,
+        _ => return Err(new_io_err("unsupported http version")),
+    };
+
+    let mut builder = http::request::Builder::new()
+        .method(request.method.unwrap())
+        .uri(request.path.unwrap())
+        .version(version);
+    std::mem::swap(builder.headers_mut().unwrap(), &mut headers);
+
+    let request = builder.body(()).unwrap();
+
+    Ok((request, head_n))
+}
+
+fn map_io_err(e: impl std::error::Error) -> Error {
+    new_io_err(&e.to_string())
+}
+
+fn new_io_err<T>(reason: T) -> Error
+where
+    T: Into<String>,
+{
+    Error::new(ErrorKind::Other, reason.into())
+}
diff --git a/client/src/main.rs b/client/src/main.rs
index e2df8b2..293e518 100644
--- a/client/src/main.rs
+++ b/client/src/main.rs
@@ -4,6 +4,7 @@ use std::{env, process};
 mod certificate;
 mod config;
 mod relay;
+mod http;
 mod socks5;
 
 #[tokio::main]
diff --git a/client/src/socks5/mod.rs b/client/src/socks5/mod.rs
index b7ec5e6..030f2c4 100644
--- a/client/src/socks5/mod.rs
+++ b/client/src/socks5/mod.rs
@@ -49,17 +49,6 @@ impl Socks5 {
     }
 
     async fn run(self) {
-        async fn handle_connection(
-            conn: IncomingConnection,
-            req_tx: Sender<RelayRequest>,
-        ) -> Result<()> {
-            match conn.handshake().await? {
-                Connection::Connect(conn, addr) => connect::handle(conn, req_tx, addr).await,
-                Connection::Bind(conn, addr) => bind::handle(conn, req_tx, addr).await,
-                Connection::Associate(conn, addr) => associate::handle(conn, req_tx, addr).await,
-            }
-        }
-
         match self.server.local_addr() {
             Ok(addr) => log::info!("[socks5] Started. Listening: {addr}"),
             Err(err) => {
@@ -91,3 +80,44 @@ impl Socks5 {
         }
     }
 }
+
+async fn handle_connection(
+    mut conn: IncomingConnection,
+    req_tx: Sender<RelayRequest>,
+) -> Result<()> {
+    let mut buf = [0u8; 4];
+    let stream = dirty::steal_stream(&mut conn);
+
+    let n = stream.peek(&mut buf).await?;
+    if n == 0 {
+        return Ok(());
+    }
+
+    // http
+    if buf[0] != 0x05 {
+        return crate::http::handle(stream, req_tx).await;
+    }
+
+    // socks5
+    match conn.handshake().await? {
+        Connection::Connect(conn, addr) => connect::handle(conn, req_tx, addr).await,
+        Connection::Bind(conn, addr) => bind::handle(conn, req_tx, addr).await,
+        Connection::Associate(conn, addr) => associate::handle(conn, req_tx, addr).await,
+    }
+}
+
+mod dirty {
+    use socks5_server::{Auth, IncomingConnection};
+    use std::sync::Arc;
+    use tokio::net::TcpStream;
+
+    struct Mirror {
+        stream: TcpStream,
+        _auth: Arc<dyn Auth + Send + Sync>,
+    }
+
+    pub fn steal_stream(conn: &mut IncomingConnection) -> &mut TcpStream {
+        let mirror: &mut Mirror = unsafe { std::mem::transmute(conn) };
+        &mut mirror.stream
+    }
+}
-- 
2.38.1

```

</details>

**Comment by Fhokud** [comment]
> 我这有个自用的补丁， 可以实现Socks5/HTTP同端口入站
> 
> <details>
> <summary>Patch</summary>
> 
> ```diff
> From 730b40f1fb736ac7f97cf43783ae843236575ef1 Mon Sep 17 00:00:00 2001
> From: zephyr <i@zephyr.moe>
> Date: Fri, 26 Aug 2022 00:56:19 +0900
> Subject: [PATCH] add http inbound
> 
> ---
>  client/Cargo.toml        |   3 +
>  client/src/http/mod.rs   | 180 +++++++++++++++++++++++++++++++++++++++
>  client/src/main.rs       |   1 +
>  client/src/socks5/mod.rs |  52 ++++++++---
>  4 files changed, 225 insertions(+), 11 deletions(-)
>  create mode 100644 client/src/http/mod.rs
> 
> diff --git a/client/Cargo.toml b/client/Cargo.toml
> index 1e11d5a..574a7f5 100644
> --- a/client/Cargo.toml
> +++ b/client/Cargo.toml
> @@ -35,3 +35,6 @@ socks5-server = "0.8.*"
>  thiserror = "1.0.*"
>  tokio = { version = "1.20.*", features = ["io-util", "macros", "net", "parking_lot", "rt-multi-thread", "sync", "time"] }
>  webpki = { version = "0.22.*", default-features = false }
> +
> +http = "0.2"
> +httparse = "1"
> diff --git a/client/src/http/mod.rs b/client/src/http/mod.rs
> new file mode 100644
> index 0000000..c230b04
> --- /dev/null
> +++ b/client/src/http/mod.rs
> @@ -0,0 +1,180 @@
> +use std::io::{Error, ErrorKind, Result};
> +
> +use tokio::io::{AsyncReadExt, AsyncWriteExt};
> +use tokio::net::TcpStream;
> +use tokio::sync::mpsc::Sender;
> +
> +use http::header::{HeaderMap, HeaderName, HeaderValue};
> +use http::request::{Parts, Request};
> +use http::{Method, Version};
> +
> +use crate::relay::Address as ProxyAddress;
> +use crate::relay::Request as ProxyRequest;
> +
> +pub async fn handle(stream: &mut TcpStream, req_tx: Sender<ProxyRequest>) -> Result<()> {
> +    let mut buf = vec![0u8; 0x2000];
> +    let n = stream.read(&mut buf).await?;
> +
> +    let (mut request, head_n) = parse_request(&buf[..n])?;
> +
> +    // connect https
> +    if request.method() == Method::CONNECT && request.version() == Version::HTTP_11 {
> +        let addr = ProxyAddress::DomainAddress(
> +            request.uri().host().unwrap().into(),
> +            request.uri().port_u16().unwrap_or(443),
> +        );
> +        return handle_connect(stream, req_tx, addr).await;
> +    }
> +
> +    // forward http
> +    rm_proxy_hdrs(request.headers_mut());
> +    // buf: 0 .. head_m .. head_n .. m .. n
> +    let (parts, _) = request.into_parts();
> +    let head_m = write_request_hdr(&parts, &mut buf[..head_n]);
> +    let m = n - (head_n - head_m);
> +    unsafe {
> +        let count = m - head_m;
> +        let src = buf.as_ptr().add(head_n);
> +        let dst = buf.as_mut_ptr().add(head_m);
> +        std::ptr::copy(src, dst, count);
> +    };
> +    let addr = ProxyAddress::DomainAddress(
> +        parts.uri.host().unwrap().into(),
> +        parts.uri.port_u16().unwrap_or(80),
> +    );
> +
> +    log::info!(
> +        "[http] [{}] [{}] [{}]",
> +        stream.peer_addr().unwrap(),
> +        parts.method.as_str(),
> +        &addr
> +    );
> +
> +    let (req, rx) = ProxyRequest::new_connect(addr);
> +    let _ = req_tx.send(req).await;
> +
> +    let mut quic_stream = rx.await.map_err(map_io_err)?;
> +    quic_stream.write_all(&buf[..m]).await?;
> +    tokio::io::copy_bidirectional(stream, &mut quic_stream).await?;
> +
> +    Ok(())
> +}
> +
> +async fn handle_connect(
> +    stream: &mut TcpStream,
> +    req_tx: Sender<ProxyRequest>,
> +    addr: ProxyAddress,
> +) -> Result<()> {
> +    log::info!(
> +        "[http] [{}] [CONNECT] [{}]",
> +        stream.peer_addr().unwrap(),
> +        &addr
> +    );
> +
> +    let (req, rx) = ProxyRequest::new_connect(addr);
> +    let _ = req_tx.send(req).await;
> +
> +    let mut quic_stream = rx.await.map_err(map_io_err)?;
> +    stream
> +        .write_all(b"HTTP/1.1 200 Connection Established\r\n\r\n")
> +        .await?;
> +
> +    tokio::io::copy_bidirectional(stream, &mut quic_stream)
> +        .await
> +        .map(|_| ())
> +}
> +
> +fn rm_proxy_hdrs(headers: &mut HeaderMap) {
> +    headers.remove("proxy-connection");
> +    headers.remove("proxy-authenticate");
> +    headers.remove("proxy-authorization");
> +    headers.remove("te");
> +    headers.remove("trailers");
> +    headers.remove("transfer-encoding");
> +    headers.remove("upgrade");
> +
> +    if let Some(keys) = headers.remove("connection") {
> +        let keys = std::str::from_utf8(keys.as_bytes()).unwrap();
> +        for key in keys.split(',').map(str::trim) {
> +            headers.remove(key);
> +        }
> +    }
> +}
> +
> +fn write_request_hdr(parts: &Parts, mut buf: &mut [u8]) -> usize {
> +    use std::io::Write;
> +    let mut n = 0;
> +
> +    macro_rules! w {
> +        ( $b: expr $(, $bx: expr)* ) => {
> +            n += buf.write($b).unwrap();
> +            $(
> +                n += buf.write($bx).unwrap();
> +            )*
> +        };
> +    }
> +
> +    // first line
> +    let method = parts.method.as_str().as_bytes();
> +    let path_query = parts.uri.path_and_query().unwrap().as_str().as_bytes();
> +    let version = match parts.version {
> +        Version::HTTP_10 => b"HTTP/1.0",
> +        Version::HTTP_11 => b"HTTP/1.1",
> +        _ => unreachable!(),
> +    };
> +    w![method, b" ", path_query, b" ", version, b"\r\n"];
> +
> +    for (key, value) in parts.headers.iter() {
> +        w!(key.as_str().as_bytes(), b": ", value.as_bytes(), b"\r\n");
> +    }
> +
> +    w!(b"\r\n");
> +
> +    n
> +}
> +
> +fn parse_request(buf: &[u8]) -> Result<(Request<()>, usize)> {
> +    use httparse::{Request, Status, EMPTY_HEADER};
> +
> +    let mut headers = [EMPTY_HEADER; 128];
> +    let mut request = Request::new(&mut headers);
> +
> +    let head_n = match request.parse(buf).map_err(map_io_err)? {
> +        Status::Complete(n) => n,
> +        Status::Partial => return Err(new_io_err("unknown protocol")),
> +    };
> +
> +    let mut headers = HeaderMap::from_iter(request.headers.iter().map(|hdr| {
> +        (
> +            HeaderName::from_bytes(hdr.name.as_bytes()).unwrap(),
> +            HeaderValue::from_bytes(hdr.value).unwrap(),
> +        )
> +    }));
> +
> +    let version = match request.version.unwrap() {
> +        0u8 => Version::HTTP_10,
> +        1u8 => Version::HTTP_11,
> +        _ => return Err(new_io_err("unsupported http version")),
> +    };
> +
> +    let mut builder = http::request::Builder::new()
> +        .method(request.method.unwrap())
> +        .uri(request.path.unwrap())
> +        .version(version);
> +    std::mem::swap(builder.headers_mut().unwrap(), &mut headers);
> +
> +    let request = builder.body(()).unwrap();
> +
> +    Ok((request, head_n))
> +}
> +
> +fn map_io_err(e: impl std::error::Error) -> Error {
> +    new_io_err(&e.to_string())
> +}
> +
> +fn new_io_err<T>(reason: T) -> Error
> +where
> +    T: Into<String>,
> +{
> +    Error::new(ErrorKind::Other, reason.into())
> +}
> diff --git a/client/src/main.rs b/client/src/main.rs
> index e2df8b2..293e518 100644
> --- a/client/src/main.rs
> +++ b/client/src/main.rs
> @@ -4,6 +4,7 @@ use std::{env, process};
>  mod certificate;
>  mod config;
>  mod relay;
> +mod http;
>  mod socks5;
>  
>  #[tokio::main]
> diff --git a/client/src/socks5/mod.rs b/client/src/socks5/mod.rs
> index b7ec5e6..030f2c4 100644
> --- a/client/src/socks5/mod.rs
> +++ b/client/src/socks5/mod.rs
> @@ -49,17 +49,6 @@ impl Socks5 {
>      }
>  
>      async fn run(self) {
> -        async fn handle_connection(
> -            conn: IncomingConnection,
> -            req_tx: Sender<RelayRequest>,
> -        ) -> Result<()> {
> -            match conn.handshake().await? {
> -                Connection::Connect(conn, addr) => connect::handle(conn, req_tx, addr).await,
> -                Connection::Bind(conn, addr) => bind::handle(conn, req_tx, addr).await,
> -                Connection::Associate(conn, addr) => associate::handle(conn, req_tx, addr).await,
> -            }
> -        }
> -
>          match self.server.local_addr() {
>              Ok(addr) => log::info!("[socks5] Started. Listening: {addr}"),
>              Err(err) => {
> @@ -91,3 +80,44 @@ impl Socks5 {
>          }
>      }
>  }
> +
> +async fn handle_connection(
> +    mut conn: IncomingConnection,
> +    req_tx: Sender<RelayRequest>,
> +) -> Result<()> {
> +    let mut buf = [0u8; 4];
> +    let stream = dirty::steal_stream(&mut conn);
> +
> +    let n = stream.peek(&mut buf).await?;
> +    if n == 0 {
> +        return Ok(());
> +    }
> +
> +    // http
> +    if buf[0] != 0x05 {
> +        return crate::http::handle(stream, req_tx).await;
> +    }
> +
> +    // socks5
> +    match conn.handshake().await? {
> +        Connection::Connect(conn, addr) => connect::handle(conn, req_tx, addr).await,
> +        Connection::Bind(conn, addr) => bind::handle(conn, req_tx, addr).await,
> +        Connection::Associate(conn, addr) => associate::handle(conn, req_tx, addr).await,
> +    }
> +}
> +
> +mod dirty {
> +    use socks5_server::{Auth, IncomingConnection};
> +    use std::sync::Arc;
> +    use tokio::net::TcpStream;
> +
> +    struct Mirror {
> +        stream: TcpStream,
> +        _auth: Arc<dyn Auth + Send + Sync>,
> +    }
> +
> +    pub fn steal_stream(conn: &mut IncomingConnection) -> &mut TcpStream {
> +        let mirror: &mut Mirror = unsafe { std::mem::transmute(conn) };
> +        &mut mirror.stream
> +    }
> +}
> -- 
> 2.38.1
> 
> ```
> 
> </details>

PR呗

**Comment by zephyrchien** [comment]
> PR一下试试呗，看作者是否接受

目前只打算自用，代码写得不是很严谨。等refactor分支完成后还需要重新适配。

**Comment by billysingo** [comment]
临时也可考虑privoxy转一下

**Comment by qingyinge-em** [comment]
> 我这有个自用的补丁， 可以实现Socks5/HTTP同端口入站
> 
> Patch

请问同一个端口处理的原理是什么？自动识别两种协议？

**Comment by zephyrchien** [comment]
> > 我这有个自用的补丁， 可以实现Socks5/HTTP同端口入站
> > Patch
> 
> 请问同一个端口处理的原理是什么？自动识别两种协议？

握手前检查第一个字节是否为0x05
